<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: identity/admin/admin.proto

namespace Auth3\Identity\Admin;

use UnexpectedValueException;

/**
 * Protobuf type <code>depot.devtools.auth.v0.identity.admin.ClientType</code>
 */
class ClientType
{
    /**
     * Generated from protobuf enum <code>CLIENT_TYPE_UNSET = 0;</code>
     */
    const CLIENT_TYPE_UNSET = 0;
    /**
     * Generated from protobuf enum <code>CLIENT_FIRST_PARTY = 1;</code>
     */
    const CLIENT_FIRST_PARTY = 1;
    /**
     * Generated from protobuf enum <code>CLIENT_THIRD_PARTY = 2;</code>
     */
    const CLIENT_THIRD_PARTY = 2;
    /**
     * Generated from protobuf enum <code>CLIENT_SYSTEM_PARTY = 3;</code>
     */
    const CLIENT_SYSTEM_PARTY = 3;

    private static $valueToName = [
        self::CLIENT_TYPE_UNSET => 'CLIENT_TYPE_UNSET',
        self::CLIENT_FIRST_PARTY => 'CLIENT_FIRST_PARTY',
        self::CLIENT_THIRD_PARTY => 'CLIENT_THIRD_PARTY',
        self::CLIENT_SYSTEM_PARTY => 'CLIENT_SYSTEM_PARTY',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

