<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: identity/admin/admin.proto

namespace Auth3\Identity\Admin;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>depot.devtools.auth.v0.identity.admin.CreateOAuth2ClientRequest</code>
 */
class CreateOAuth2ClientRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated string allowed_cors_origins = 1[json_name = "allowedCorsOrigins"];</code>
     */
    private $allowed_cors_origins;
    /**
     * Generated from protobuf field <code>repeated string audience = 2[json_name = "audience"];</code>
     */
    private $audience;
    /**
     * Generated from protobuf field <code>bool backchannel_logout_session_required = 3[json_name = "backchannelLogoutSessionRequired"];</code>
     */
    protected $backchannel_logout_session_required = false;
    /**
     * Generated from protobuf field <code>string backchannel_logout_uri = 4[json_name = "backchannelLogoutUri"];</code>
     */
    protected $backchannel_logout_uri = '';
    /**
     * Generated from protobuf field <code>string client_name = 6[json_name = "clientName"];</code>
     */
    protected $client_name = '';
    /**
     * Generated from protobuf field <code>string client_uri = 8[json_name = "clientUri"];</code>
     */
    protected $client_uri = '';
    /**
     * Generated from protobuf field <code>repeated string contacts = 9[json_name = "contacts"];</code>
     */
    private $contacts;
    /**
     * Generated from protobuf field <code>bool frontchannel_logout_session_required = 11[json_name = "frontchannelLogoutSessionRequired"];</code>
     */
    protected $frontchannel_logout_session_required = false;
    /**
     * Generated from protobuf field <code>string frontchannel_logout_uri = 12[json_name = "frontchannelLogoutUri"];</code>
     */
    protected $frontchannel_logout_uri = '';
    /**
     * Generated from protobuf field <code>repeated .depot.devtools.auth.v0.identity.admin.GrantType grant_types = 13[json_name = "grantTypes"];</code>
     */
    private $grant_types;
    /**
     * Generated from protobuf field <code>.google.protobuf.Struct jwks = 14[json_name = "jwks"];</code>
     */
    protected $jwks = null;
    /**
     * Generated from protobuf field <code>string jwks_uri = 15[json_name = "jwksUri"];</code>
     */
    protected $jwks_uri = '';
    /**
     * Generated from protobuf field <code>string logo_uri = 16[json_name = "logoUri"];</code>
     */
    protected $logo_uri = '';
    /**
     * Generated from protobuf field <code>.google.protobuf.Struct metadata = 17[json_name = "metadata"];</code>
     */
    protected $metadata = null;
    /**
     * Generated from protobuf field <code>string owner = 18[json_name = "owner"];</code>
     */
    protected $owner = '';
    /**
     * Generated from protobuf field <code>string policy_uri = 19[json_name = "policyUri"];</code>
     */
    protected $policy_uri = '';
    /**
     * Generated from protobuf field <code>repeated string post_logout_redirect_uris = 20[json_name = "postLogoutRedirectUris"];</code>
     */
    private $post_logout_redirect_uris;
    /**
     * Generated from protobuf field <code>repeated string redirect_uris = 21[json_name = "redirectUris"];</code>
     */
    private $redirect_uris;
    /**
     * Generated from protobuf field <code>.depot.devtools.auth.v0.identity.admin.RequestObjectSigningAlg request_object_signing_alg = 22[json_name = "requestObjectSigningAlg"];</code>
     */
    protected $request_object_signing_alg = 0;
    /**
     * Generated from protobuf field <code>repeated string request_uris = 23[json_name = "requestUris"];</code>
     */
    private $request_uris;
    /**
     * Generated from protobuf field <code>repeated .depot.devtools.auth.v0.identity.admin.ResponseType response_types = 24[json_name = "responseTypes"];</code>
     */
    private $response_types;
    /**
     * Generated from protobuf field <code>string scope = 25[json_name = "scope"];</code>
     */
    protected $scope = '';
    /**
     * Generated from protobuf field <code>string sector_identifier_uri = 26[json_name = "sectorIdentifierUri"];</code>
     */
    protected $sector_identifier_uri = '';
    /**
     * Generated from protobuf field <code>.depot.devtools.auth.v0.identity.admin.SubjectType subject_type = 27[json_name = "subjectType"];</code>
     */
    protected $subject_type = 0;
    /**
     * Generated from protobuf field <code>.depot.devtools.auth.v0.identity.admin.TokenEndpointAuthMethod token_endpoint_auth_method = 28[json_name = "tokenEndpointAuthMethod"];</code>
     */
    protected $token_endpoint_auth_method = 0;
    /**
     * Generated from protobuf field <code>.depot.devtools.auth.v0.identity.admin.TokenEndpointAuthSigningAlg token_endpoint_auth_signing_alg = 29[json_name = "tokenEndpointAuthSigningAlg"];</code>
     */
    protected $token_endpoint_auth_signing_alg = 0;
    /**
     * Generated from protobuf field <code>string tos_uri = 30[json_name = "tosUri"];</code>
     */
    protected $tos_uri = '';
    /**
     * Generated from protobuf field <code>.depot.devtools.auth.v0.identity.admin.UserinfoSignedResponseAlg userinfo_signed_response_alg = 31[json_name = "userinfoSignedResponseAlg"];</code>
     */
    protected $userinfo_signed_response_alg = 0;
    /**
     * Generated from protobuf field <code>string client_secret = 32[json_name = "clientSecret"];</code>
     */
    protected $client_secret = '';
    /**
     * Generated from protobuf field <code>.depot.devtools.auth.v0.identity.admin.ClientType client_type = 33[json_name = "clientType"];</code>
     */
    protected $client_type = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string[]|\Google\Protobuf\Internal\RepeatedField $allowed_cors_origins
     *     @type string[]|\Google\Protobuf\Internal\RepeatedField $audience
     *     @type bool $backchannel_logout_session_required
     *     @type string $backchannel_logout_uri
     *     @type string $client_name
     *     @type string $client_uri
     *     @type string[]|\Google\Protobuf\Internal\RepeatedField $contacts
     *     @type bool $frontchannel_logout_session_required
     *     @type string $frontchannel_logout_uri
     *     @type int[]|\Google\Protobuf\Internal\RepeatedField $grant_types
     *     @type \Google\Protobuf\Struct $jwks
     *     @type string $jwks_uri
     *     @type string $logo_uri
     *     @type \Google\Protobuf\Struct $metadata
     *     @type string $owner
     *     @type string $policy_uri
     *     @type string[]|\Google\Protobuf\Internal\RepeatedField $post_logout_redirect_uris
     *     @type string[]|\Google\Protobuf\Internal\RepeatedField $redirect_uris
     *     @type int $request_object_signing_alg
     *     @type string[]|\Google\Protobuf\Internal\RepeatedField $request_uris
     *     @type int[]|\Google\Protobuf\Internal\RepeatedField $response_types
     *     @type string $scope
     *     @type string $sector_identifier_uri
     *     @type int $subject_type
     *     @type int $token_endpoint_auth_method
     *     @type int $token_endpoint_auth_signing_alg
     *     @type string $tos_uri
     *     @type int $userinfo_signed_response_alg
     *     @type string $client_secret
     *     @type int $client_type
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Devtools\Auth\V0\Proto\Identity\Admin\Admin::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated string allowed_cors_origins = 1[json_name = "allowedCorsOrigins"];</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getAllowedCorsOrigins()
    {
        return $this->allowed_cors_origins;
    }

    /**
     * Generated from protobuf field <code>repeated string allowed_cors_origins = 1[json_name = "allowedCorsOrigins"];</code>
     * @param string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setAllowedCorsOrigins($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->allowed_cors_origins = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated string audience = 2[json_name = "audience"];</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getAudience()
    {
        return $this->audience;
    }

    /**
     * Generated from protobuf field <code>repeated string audience = 2[json_name = "audience"];</code>
     * @param string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setAudience($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->audience = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool backchannel_logout_session_required = 3[json_name = "backchannelLogoutSessionRequired"];</code>
     * @return bool
     */
    public function getBackchannelLogoutSessionRequired()
    {
        return $this->backchannel_logout_session_required;
    }

    /**
     * Generated from protobuf field <code>bool backchannel_logout_session_required = 3[json_name = "backchannelLogoutSessionRequired"];</code>
     * @param bool $var
     * @return $this
     */
    public function setBackchannelLogoutSessionRequired($var)
    {
        GPBUtil::checkBool($var);
        $this->backchannel_logout_session_required = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string backchannel_logout_uri = 4[json_name = "backchannelLogoutUri"];</code>
     * @return string
     */
    public function getBackchannelLogoutUri()
    {
        return $this->backchannel_logout_uri;
    }

    /**
     * Generated from protobuf field <code>string backchannel_logout_uri = 4[json_name = "backchannelLogoutUri"];</code>
     * @param string $var
     * @return $this
     */
    public function setBackchannelLogoutUri($var)
    {
        GPBUtil::checkString($var, True);
        $this->backchannel_logout_uri = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string client_name = 6[json_name = "clientName"];</code>
     * @return string
     */
    public function getClientName()
    {
        return $this->client_name;
    }

    /**
     * Generated from protobuf field <code>string client_name = 6[json_name = "clientName"];</code>
     * @param string $var
     * @return $this
     */
    public function setClientName($var)
    {
        GPBUtil::checkString($var, True);
        $this->client_name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string client_uri = 8[json_name = "clientUri"];</code>
     * @return string
     */
    public function getClientUri()
    {
        return $this->client_uri;
    }

    /**
     * Generated from protobuf field <code>string client_uri = 8[json_name = "clientUri"];</code>
     * @param string $var
     * @return $this
     */
    public function setClientUri($var)
    {
        GPBUtil::checkString($var, True);
        $this->client_uri = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated string contacts = 9[json_name = "contacts"];</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getContacts()
    {
        return $this->contacts;
    }

    /**
     * Generated from protobuf field <code>repeated string contacts = 9[json_name = "contacts"];</code>
     * @param string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setContacts($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->contacts = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool frontchannel_logout_session_required = 11[json_name = "frontchannelLogoutSessionRequired"];</code>
     * @return bool
     */
    public function getFrontchannelLogoutSessionRequired()
    {
        return $this->frontchannel_logout_session_required;
    }

    /**
     * Generated from protobuf field <code>bool frontchannel_logout_session_required = 11[json_name = "frontchannelLogoutSessionRequired"];</code>
     * @param bool $var
     * @return $this
     */
    public function setFrontchannelLogoutSessionRequired($var)
    {
        GPBUtil::checkBool($var);
        $this->frontchannel_logout_session_required = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string frontchannel_logout_uri = 12[json_name = "frontchannelLogoutUri"];</code>
     * @return string
     */
    public function getFrontchannelLogoutUri()
    {
        return $this->frontchannel_logout_uri;
    }

    /**
     * Generated from protobuf field <code>string frontchannel_logout_uri = 12[json_name = "frontchannelLogoutUri"];</code>
     * @param string $var
     * @return $this
     */
    public function setFrontchannelLogoutUri($var)
    {
        GPBUtil::checkString($var, True);
        $this->frontchannel_logout_uri = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .depot.devtools.auth.v0.identity.admin.GrantType grant_types = 13[json_name = "grantTypes"];</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getGrantTypes()
    {
        return $this->grant_types;
    }

    /**
     * Generated from protobuf field <code>repeated .depot.devtools.auth.v0.identity.admin.GrantType grant_types = 13[json_name = "grantTypes"];</code>
     * @param int[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setGrantTypes($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::ENUM, \Auth3\Identity\Admin\GrantType::class);
        $this->grant_types = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Struct jwks = 14[json_name = "jwks"];</code>
     * @return \Google\Protobuf\Struct
     */
    public function getJwks()
    {
        return $this->jwks;
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Struct jwks = 14[json_name = "jwks"];</code>
     * @param \Google\Protobuf\Struct $var
     * @return $this
     */
    public function setJwks($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Struct::class);
        $this->jwks = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string jwks_uri = 15[json_name = "jwksUri"];</code>
     * @return string
     */
    public function getJwksUri()
    {
        return $this->jwks_uri;
    }

    /**
     * Generated from protobuf field <code>string jwks_uri = 15[json_name = "jwksUri"];</code>
     * @param string $var
     * @return $this
     */
    public function setJwksUri($var)
    {
        GPBUtil::checkString($var, True);
        $this->jwks_uri = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string logo_uri = 16[json_name = "logoUri"];</code>
     * @return string
     */
    public function getLogoUri()
    {
        return $this->logo_uri;
    }

    /**
     * Generated from protobuf field <code>string logo_uri = 16[json_name = "logoUri"];</code>
     * @param string $var
     * @return $this
     */
    public function setLogoUri($var)
    {
        GPBUtil::checkString($var, True);
        $this->logo_uri = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Struct metadata = 17[json_name = "metadata"];</code>
     * @return \Google\Protobuf\Struct
     */
    public function getMetadata()
    {
        return $this->metadata;
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Struct metadata = 17[json_name = "metadata"];</code>
     * @param \Google\Protobuf\Struct $var
     * @return $this
     */
    public function setMetadata($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Struct::class);
        $this->metadata = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string owner = 18[json_name = "owner"];</code>
     * @return string
     */
    public function getOwner()
    {
        return $this->owner;
    }

    /**
     * Generated from protobuf field <code>string owner = 18[json_name = "owner"];</code>
     * @param string $var
     * @return $this
     */
    public function setOwner($var)
    {
        GPBUtil::checkString($var, True);
        $this->owner = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string policy_uri = 19[json_name = "policyUri"];</code>
     * @return string
     */
    public function getPolicyUri()
    {
        return $this->policy_uri;
    }

    /**
     * Generated from protobuf field <code>string policy_uri = 19[json_name = "policyUri"];</code>
     * @param string $var
     * @return $this
     */
    public function setPolicyUri($var)
    {
        GPBUtil::checkString($var, True);
        $this->policy_uri = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated string post_logout_redirect_uris = 20[json_name = "postLogoutRedirectUris"];</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getPostLogoutRedirectUris()
    {
        return $this->post_logout_redirect_uris;
    }

    /**
     * Generated from protobuf field <code>repeated string post_logout_redirect_uris = 20[json_name = "postLogoutRedirectUris"];</code>
     * @param string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setPostLogoutRedirectUris($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->post_logout_redirect_uris = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated string redirect_uris = 21[json_name = "redirectUris"];</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getRedirectUris()
    {
        return $this->redirect_uris;
    }

    /**
     * Generated from protobuf field <code>repeated string redirect_uris = 21[json_name = "redirectUris"];</code>
     * @param string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setRedirectUris($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->redirect_uris = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.depot.devtools.auth.v0.identity.admin.RequestObjectSigningAlg request_object_signing_alg = 22[json_name = "requestObjectSigningAlg"];</code>
     * @return int
     */
    public function getRequestObjectSigningAlg()
    {
        return $this->request_object_signing_alg;
    }

    /**
     * Generated from protobuf field <code>.depot.devtools.auth.v0.identity.admin.RequestObjectSigningAlg request_object_signing_alg = 22[json_name = "requestObjectSigningAlg"];</code>
     * @param int $var
     * @return $this
     */
    public function setRequestObjectSigningAlg($var)
    {
        GPBUtil::checkEnum($var, \Auth3\Identity\Admin\RequestObjectSigningAlg::class);
        $this->request_object_signing_alg = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated string request_uris = 23[json_name = "requestUris"];</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getRequestUris()
    {
        return $this->request_uris;
    }

    /**
     * Generated from protobuf field <code>repeated string request_uris = 23[json_name = "requestUris"];</code>
     * @param string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setRequestUris($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->request_uris = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .depot.devtools.auth.v0.identity.admin.ResponseType response_types = 24[json_name = "responseTypes"];</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getResponseTypes()
    {
        return $this->response_types;
    }

    /**
     * Generated from protobuf field <code>repeated .depot.devtools.auth.v0.identity.admin.ResponseType response_types = 24[json_name = "responseTypes"];</code>
     * @param int[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setResponseTypes($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::ENUM, \Auth3\Identity\Admin\ResponseType::class);
        $this->response_types = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string scope = 25[json_name = "scope"];</code>
     * @return string
     */
    public function getScope()
    {
        return $this->scope;
    }

    /**
     * Generated from protobuf field <code>string scope = 25[json_name = "scope"];</code>
     * @param string $var
     * @return $this
     */
    public function setScope($var)
    {
        GPBUtil::checkString($var, True);
        $this->scope = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string sector_identifier_uri = 26[json_name = "sectorIdentifierUri"];</code>
     * @return string
     */
    public function getSectorIdentifierUri()
    {
        return $this->sector_identifier_uri;
    }

    /**
     * Generated from protobuf field <code>string sector_identifier_uri = 26[json_name = "sectorIdentifierUri"];</code>
     * @param string $var
     * @return $this
     */
    public function setSectorIdentifierUri($var)
    {
        GPBUtil::checkString($var, True);
        $this->sector_identifier_uri = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.depot.devtools.auth.v0.identity.admin.SubjectType subject_type = 27[json_name = "subjectType"];</code>
     * @return int
     */
    public function getSubjectType()
    {
        return $this->subject_type;
    }

    /**
     * Generated from protobuf field <code>.depot.devtools.auth.v0.identity.admin.SubjectType subject_type = 27[json_name = "subjectType"];</code>
     * @param int $var
     * @return $this
     */
    public function setSubjectType($var)
    {
        GPBUtil::checkEnum($var, \Auth3\Identity\Admin\SubjectType::class);
        $this->subject_type = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.depot.devtools.auth.v0.identity.admin.TokenEndpointAuthMethod token_endpoint_auth_method = 28[json_name = "tokenEndpointAuthMethod"];</code>
     * @return int
     */
    public function getTokenEndpointAuthMethod()
    {
        return $this->token_endpoint_auth_method;
    }

    /**
     * Generated from protobuf field <code>.depot.devtools.auth.v0.identity.admin.TokenEndpointAuthMethod token_endpoint_auth_method = 28[json_name = "tokenEndpointAuthMethod"];</code>
     * @param int $var
     * @return $this
     */
    public function setTokenEndpointAuthMethod($var)
    {
        GPBUtil::checkEnum($var, \Auth3\Identity\Admin\TokenEndpointAuthMethod::class);
        $this->token_endpoint_auth_method = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.depot.devtools.auth.v0.identity.admin.TokenEndpointAuthSigningAlg token_endpoint_auth_signing_alg = 29[json_name = "tokenEndpointAuthSigningAlg"];</code>
     * @return int
     */
    public function getTokenEndpointAuthSigningAlg()
    {
        return $this->token_endpoint_auth_signing_alg;
    }

    /**
     * Generated from protobuf field <code>.depot.devtools.auth.v0.identity.admin.TokenEndpointAuthSigningAlg token_endpoint_auth_signing_alg = 29[json_name = "tokenEndpointAuthSigningAlg"];</code>
     * @param int $var
     * @return $this
     */
    public function setTokenEndpointAuthSigningAlg($var)
    {
        GPBUtil::checkEnum($var, \Auth3\Identity\Admin\TokenEndpointAuthSigningAlg::class);
        $this->token_endpoint_auth_signing_alg = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string tos_uri = 30[json_name = "tosUri"];</code>
     * @return string
     */
    public function getTosUri()
    {
        return $this->tos_uri;
    }

    /**
     * Generated from protobuf field <code>string tos_uri = 30[json_name = "tosUri"];</code>
     * @param string $var
     * @return $this
     */
    public function setTosUri($var)
    {
        GPBUtil::checkString($var, True);
        $this->tos_uri = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.depot.devtools.auth.v0.identity.admin.UserinfoSignedResponseAlg userinfo_signed_response_alg = 31[json_name = "userinfoSignedResponseAlg"];</code>
     * @return int
     */
    public function getUserinfoSignedResponseAlg()
    {
        return $this->userinfo_signed_response_alg;
    }

    /**
     * Generated from protobuf field <code>.depot.devtools.auth.v0.identity.admin.UserinfoSignedResponseAlg userinfo_signed_response_alg = 31[json_name = "userinfoSignedResponseAlg"];</code>
     * @param int $var
     * @return $this
     */
    public function setUserinfoSignedResponseAlg($var)
    {
        GPBUtil::checkEnum($var, \Auth3\Identity\Admin\UserinfoSignedResponseAlg::class);
        $this->userinfo_signed_response_alg = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string client_secret = 32[json_name = "clientSecret"];</code>
     * @return string
     */
    public function getClientSecret()
    {
        return $this->client_secret;
    }

    /**
     * Generated from protobuf field <code>string client_secret = 32[json_name = "clientSecret"];</code>
     * @param string $var
     * @return $this
     */
    public function setClientSecret($var)
    {
        GPBUtil::checkString($var, True);
        $this->client_secret = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.depot.devtools.auth.v0.identity.admin.ClientType client_type = 33[json_name = "clientType"];</code>
     * @return int
     */
    public function getClientType()
    {
        return $this->client_type;
    }

    /**
     * Generated from protobuf field <code>.depot.devtools.auth.v0.identity.admin.ClientType client_type = 33[json_name = "clientType"];</code>
     * @param int $var
     * @return $this
     */
    public function setClientType($var)
    {
        GPBUtil::checkEnum($var, \Auth3\Identity\Admin\ClientType::class);
        $this->client_type = $var;

        return $this;
    }

}

