<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: identity/admin/admin.proto

namespace Auth3\Identity\Admin;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>depot.devtools.auth.v0.identity.admin.CreateConnectionRequest</code>
 */
class CreateConnectionRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string name = 1[json_name = "name"];</code>
     */
    protected $name = '';
    /**
     * Generated from protobuf field <code>string client_id = 2[json_name = "clientId"];</code>
     */
    protected $client_id = '';
    /**
     * Generated from protobuf field <code>string client_secret = 3[json_name = "clientSecret"];</code>
     */
    protected $client_secret = '';
    /**
     * Generated from protobuf field <code>string button_image_url = 4[json_name = "buttonImageUrl"];</code>
     */
    protected $button_image_url = '';
    /**
     * Generated from protobuf field <code>.depot.devtools.auth.v0.identity.admin.CreateConnectionRequest.Providers provider = 6[json_name = "provider"];</code>
     */
    protected $provider = 0;
    /**
     * Generated from protobuf field <code>string oidc_discovery_url = 7[json_name = "oidcDiscoveryUrl"];</code>
     */
    protected $oidc_discovery_url = '';
    /**
     * Generated from protobuf field <code>repeated string mfa = 8[json_name = "mfa"];</code>
     */
    private $mfa;
    /**
     * Generated from protobuf field <code>.depot.devtools.auth.v0.identity.admin.CreateConnectionRequest.Types type = 9[json_name = "type"];</code>
     */
    protected $type = 0;
    /**
     * Generated from protobuf field <code>string scopes = 10[json_name = "scopes"];</code>
     */
    protected $scopes = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $name
     *     @type string $client_id
     *     @type string $client_secret
     *     @type string $button_image_url
     *     @type int $provider
     *     @type string $oidc_discovery_url
     *     @type string[]|\Google\Protobuf\Internal\RepeatedField $mfa
     *     @type int $type
     *     @type string $scopes
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Devtools\Auth\V0\Proto\Identity\Admin\Admin::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string name = 1[json_name = "name"];</code>
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Generated from protobuf field <code>string name = 1[json_name = "name"];</code>
     * @param string $var
     * @return $this
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string client_id = 2[json_name = "clientId"];</code>
     * @return string
     */
    public function getClientId()
    {
        return $this->client_id;
    }

    /**
     * Generated from protobuf field <code>string client_id = 2[json_name = "clientId"];</code>
     * @param string $var
     * @return $this
     */
    public function setClientId($var)
    {
        GPBUtil::checkString($var, True);
        $this->client_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string client_secret = 3[json_name = "clientSecret"];</code>
     * @return string
     */
    public function getClientSecret()
    {
        return $this->client_secret;
    }

    /**
     * Generated from protobuf field <code>string client_secret = 3[json_name = "clientSecret"];</code>
     * @param string $var
     * @return $this
     */
    public function setClientSecret($var)
    {
        GPBUtil::checkString($var, True);
        $this->client_secret = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string button_image_url = 4[json_name = "buttonImageUrl"];</code>
     * @return string
     */
    public function getButtonImageUrl()
    {
        return $this->button_image_url;
    }

    /**
     * Generated from protobuf field <code>string button_image_url = 4[json_name = "buttonImageUrl"];</code>
     * @param string $var
     * @return $this
     */
    public function setButtonImageUrl($var)
    {
        GPBUtil::checkString($var, True);
        $this->button_image_url = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.depot.devtools.auth.v0.identity.admin.CreateConnectionRequest.Providers provider = 6[json_name = "provider"];</code>
     * @return int
     */
    public function getProvider()
    {
        return $this->provider;
    }

    /**
     * Generated from protobuf field <code>.depot.devtools.auth.v0.identity.admin.CreateConnectionRequest.Providers provider = 6[json_name = "provider"];</code>
     * @param int $var
     * @return $this
     */
    public function setProvider($var)
    {
        GPBUtil::checkEnum($var, \Auth3\Identity\Admin\CreateConnectionRequest\Providers::class);
        $this->provider = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string oidc_discovery_url = 7[json_name = "oidcDiscoveryUrl"];</code>
     * @return string
     */
    public function getOidcDiscoveryUrl()
    {
        return $this->oidc_discovery_url;
    }

    /**
     * Generated from protobuf field <code>string oidc_discovery_url = 7[json_name = "oidcDiscoveryUrl"];</code>
     * @param string $var
     * @return $this
     */
    public function setOidcDiscoveryUrl($var)
    {
        GPBUtil::checkString($var, True);
        $this->oidc_discovery_url = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated string mfa = 8[json_name = "mfa"];</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getMfa()
    {
        return $this->mfa;
    }

    /**
     * Generated from protobuf field <code>repeated string mfa = 8[json_name = "mfa"];</code>
     * @param string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setMfa($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->mfa = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.depot.devtools.auth.v0.identity.admin.CreateConnectionRequest.Types type = 9[json_name = "type"];</code>
     * @return int
     */
    public function getType()
    {
        return $this->type;
    }

    /**
     * Generated from protobuf field <code>.depot.devtools.auth.v0.identity.admin.CreateConnectionRequest.Types type = 9[json_name = "type"];</code>
     * @param int $var
     * @return $this
     */
    public function setType($var)
    {
        GPBUtil::checkEnum($var, \Auth3\Identity\Admin\CreateConnectionRequest\Types::class);
        $this->type = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string scopes = 10[json_name = "scopes"];</code>
     * @return string
     */
    public function getScopes()
    {
        return $this->scopes;
    }

    /**
     * Generated from protobuf field <code>string scopes = 10[json_name = "scopes"];</code>
     * @param string $var
     * @return $this
     */
    public function setScopes($var)
    {
        GPBUtil::checkString($var, True);
        $this->scopes = $var;

        return $this;
    }

}

