<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: identity/admin/admin.proto

namespace Auth3\Identity\Admin;

if (false) {
    /**
     * This class is deprecated. Use Auth3\Identity\Admin\CreateConnectionRequest\Providers instead.
     * @deprecated
     */
    class CreateConnectionRequest_Providers {}
}
class_exists(CreateConnectionRequest\Providers::class);
@trigger_error('Auth3\Identity\Admin\CreateConnectionRequest_Providers is deprecated and will be removed in the next major release. Use Auth3\Identity\Admin\CreateConnectionRequest\Providers instead', E_USER_DEPRECATED);

