<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: identity/admin/admin.proto

namespace Auth3\Identity\Admin;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>depot.devtools.auth.v0.identity.admin.CreateIdentityRequest</code>
 */
class CreateIdentityRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.google.protobuf.Struct data = 1[json_name = "data"];</code>
     */
    protected $data = null;
    /**
     * Generated from protobuf field <code>string connection_id = 2[json_name = "connectionId"];</code>
     */
    protected $connection_id = '';
    /**
     * Generated from protobuf field <code>string schema_id = 3[json_name = "schemaId"];</code>
     */
    protected $schema_id = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Google\Protobuf\Struct $data
     *     @type string $connection_id
     *     @type string $schema_id
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Devtools\Auth\V0\Proto\Identity\Admin\Admin::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Struct data = 1[json_name = "data"];</code>
     * @return \Google\Protobuf\Struct
     */
    public function getData()
    {
        return $this->data;
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Struct data = 1[json_name = "data"];</code>
     * @param \Google\Protobuf\Struct $var
     * @return $this
     */
    public function setData($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Struct::class);
        $this->data = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string connection_id = 2[json_name = "connectionId"];</code>
     * @return string
     */
    public function getConnectionId()
    {
        return $this->connection_id;
    }

    /**
     * Generated from protobuf field <code>string connection_id = 2[json_name = "connectionId"];</code>
     * @param string $var
     * @return $this
     */
    public function setConnectionId($var)
    {
        GPBUtil::checkString($var, True);
        $this->connection_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string schema_id = 3[json_name = "schemaId"];</code>
     * @return string
     */
    public function getSchemaId()
    {
        return $this->schema_id;
    }

    /**
     * Generated from protobuf field <code>string schema_id = 3[json_name = "schemaId"];</code>
     * @param string $var
     * @return $this
     */
    public function setSchemaId($var)
    {
        GPBUtil::checkString($var, True);
        $this->schema_id = $var;

        return $this;
    }

}

