<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: identity/admin/admin.proto

namespace Auth3\Identity\Admin;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>depot.devtools.auth.v0.identity.admin.GetAddressResponse</code>
 */
class GetAddressResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string id = 1[json_name = "id"];</code>
     */
    protected $id = '';
    /**
     * Generated from protobuf field <code>string identity_id = 2[json_name = "identityId"];</code>
     */
    protected $identity_id = '';
    /**
     * Generated from protobuf field <code>string name = 3[json_name = "name"];</code>
     */
    protected $name = '';
    /**
     * Generated from protobuf field <code>string address = 4[json_name = "address"];</code>
     */
    protected $address = '';
    /**
     * Generated from protobuf field <code>bool verified = 5[json_name = "verified"];</code>
     */
    protected $verified = false;
    /**
     * Generated from protobuf field <code>string id_schema_key = 6[json_name = "idSchemaKey"];</code>
     */
    protected $id_schema_key = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $id
     *     @type string $identity_id
     *     @type string $name
     *     @type string $address
     *     @type bool $verified
     *     @type string $id_schema_key
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Devtools\Auth\V0\Proto\Identity\Admin\Admin::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string id = 1[json_name = "id"];</code>
     * @return string
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Generated from protobuf field <code>string id = 1[json_name = "id"];</code>
     * @param string $var
     * @return $this
     */
    public function setId($var)
    {
        GPBUtil::checkString($var, True);
        $this->id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string identity_id = 2[json_name = "identityId"];</code>
     * @return string
     */
    public function getIdentityId()
    {
        return $this->identity_id;
    }

    /**
     * Generated from protobuf field <code>string identity_id = 2[json_name = "identityId"];</code>
     * @param string $var
     * @return $this
     */
    public function setIdentityId($var)
    {
        GPBUtil::checkString($var, True);
        $this->identity_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string name = 3[json_name = "name"];</code>
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Generated from protobuf field <code>string name = 3[json_name = "name"];</code>
     * @param string $var
     * @return $this
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string address = 4[json_name = "address"];</code>
     * @return string
     */
    public function getAddress()
    {
        return $this->address;
    }

    /**
     * Generated from protobuf field <code>string address = 4[json_name = "address"];</code>
     * @param string $var
     * @return $this
     */
    public function setAddress($var)
    {
        GPBUtil::checkString($var, True);
        $this->address = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool verified = 5[json_name = "verified"];</code>
     * @return bool
     */
    public function getVerified()
    {
        return $this->verified;
    }

    /**
     * Generated from protobuf field <code>bool verified = 5[json_name = "verified"];</code>
     * @param bool $var
     * @return $this
     */
    public function setVerified($var)
    {
        GPBUtil::checkBool($var);
        $this->verified = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string id_schema_key = 6[json_name = "idSchemaKey"];</code>
     * @return string
     */
    public function getIdSchemaKey()
    {
        return $this->id_schema_key;
    }

    /**
     * Generated from protobuf field <code>string id_schema_key = 6[json_name = "idSchemaKey"];</code>
     * @param string $var
     * @return $this
     */
    public function setIdSchemaKey($var)
    {
        GPBUtil::checkString($var, True);
        $this->id_schema_key = $var;

        return $this;
    }

}

