<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: identity/admin/admin.proto

namespace Auth3\Identity\Admin;

if (false) {
    /**
     * This class is deprecated. Use Auth3\Identity\Admin\GetAddressesResponse\Address instead.
     * @deprecated
     */
    class GetAddressesResponse_Address {}
}
class_exists(GetAddressesResponse\Address::class);
@trigger_error('Auth3\Identity\Admin\GetAddressesResponse_Address is deprecated and will be removed in the next major release. Use Auth3\Identity\Admin\GetAddressesResponse\Address instead', E_USER_DEPRECATED);

