<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: identity/admin/admin.proto

namespace Auth3\Identity\Admin;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>depot.devtools.auth.v0.identity.admin.GetAddressesResponse</code>
 */
class GetAddressesResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .depot.devtools.auth.v0.identity.admin.GetAddressesResponse.Address addresses = 1[json_name = "addresses"];</code>
     */
    private $addresses;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Auth3\Identity\Admin\GetAddressesResponse\Address[]|\Google\Protobuf\Internal\RepeatedField $addresses
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Devtools\Auth\V0\Proto\Identity\Admin\Admin::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .depot.devtools.auth.v0.identity.admin.GetAddressesResponse.Address addresses = 1[json_name = "addresses"];</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getAddresses()
    {
        return $this->addresses;
    }

    /**
     * Generated from protobuf field <code>repeated .depot.devtools.auth.v0.identity.admin.GetAddressesResponse.Address addresses = 1[json_name = "addresses"];</code>
     * @param \Auth3\Identity\Admin\GetAddressesResponse\Address[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setAddresses($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Auth3\Identity\Admin\GetAddressesResponse\Address::class);
        $this->addresses = $arr;

        return $this;
    }

}

