<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: identity/admin/admin.proto

namespace Auth3\Identity\Admin;

if (false) {
    /**
     * This class is deprecated. Use Auth3\Identity\Admin\GetConnectionsResponse\Purposes instead.
     * @deprecated
     */
    class GetConnectionsResponse_Purposes {}
}
class_exists(GetConnectionsResponse\Purposes::class);
@trigger_error('Auth3\Identity\Admin\GetConnectionsResponse_Purposes is deprecated and will be removed in the next major release. Use Auth3\Identity\Admin\GetConnectionsResponse\Purposes instead', E_USER_DEPRECATED);

