<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: identity/admin/admin.proto

namespace Auth3\Identity\Admin;

if (false) {
    /**
     * This class is deprecated. Use Auth3\Identity\Admin\GetCredentialsResponse\Credential instead.
     * @deprecated
     */
    class GetCredentialsResponse_Credential {}
}
class_exists(GetCredentialsResponse\Credential::class);
@trigger_error('Auth3\Identity\Admin\GetCredentialsResponse_Credential is deprecated and will be removed in the next major release. Use Auth3\Identity\Admin\GetCredentialsResponse\Credential instead', E_USER_DEPRECATED);

