<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: identity/admin/admin.proto

namespace Auth3\Identity\Admin;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>depot.devtools.auth.v0.identity.admin.GetCredentialsResponse</code>
 */
class GetCredentialsResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>map<string, .depot.devtools.auth.v0.identity.admin.GetCredentialsResponse.Credential> credentials = 1[json_name = "credentials"];</code>
     */
    private $credentials;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type array|\Google\Protobuf\Internal\MapField $credentials
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Devtools\Auth\V0\Proto\Identity\Admin\Admin::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>map<string, .depot.devtools.auth.v0.identity.admin.GetCredentialsResponse.Credential> credentials = 1[json_name = "credentials"];</code>
     * @return \Google\Protobuf\Internal\MapField
     */
    public function getCredentials()
    {
        return $this->credentials;
    }

    /**
     * Generated from protobuf field <code>map<string, .depot.devtools.auth.v0.identity.admin.GetCredentialsResponse.Credential> credentials = 1[json_name = "credentials"];</code>
     * @param array|\Google\Protobuf\Internal\MapField $var
     * @return $this
     */
    public function setCredentials($var)
    {
        $arr = GPBUtil::checkMapField($var, \Google\Protobuf\Internal\GPBType::STRING, \Google\Protobuf\Internal\GPBType::MESSAGE, \Auth3\Identity\Admin\GetCredentialsResponse\Credential::class);
        $this->credentials = $arr;

        return $this;
    }

}

