<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: identity/admin/admin.proto

namespace Auth3\Identity\Admin;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>depot.devtools.auth.v0.identity.admin.GetConnectionsResponse</code>
 */
class GetConnectionsResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .depot.devtools.auth.v0.identity.admin.GetConnectionsResponse.Connection connections = 1[json_name = "connections"];</code>
     */
    private $connections;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Auth3\Identity\Admin\GetConnectionsResponse\Connection[]|\Google\Protobuf\Internal\RepeatedField $connections
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Devtools\Auth\V0\Proto\Identity\Admin\Admin::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .depot.devtools.auth.v0.identity.admin.GetConnectionsResponse.Connection connections = 1[json_name = "connections"];</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getConnections()
    {
        return $this->connections;
    }

    /**
     * Generated from protobuf field <code>repeated .depot.devtools.auth.v0.identity.admin.GetConnectionsResponse.Connection connections = 1[json_name = "connections"];</code>
     * @param \Auth3\Identity\Admin\GetConnectionsResponse\Connection[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setConnections($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Auth3\Identity\Admin\GetConnectionsResponse\Connection::class);
        $this->connections = $arr;

        return $this;
    }

}

