<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: identity/admin/admin.proto

namespace Auth3\Identity\Admin;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>depot.devtools.auth.v0.identity.admin.GetIdSchemasResponse</code>
 */
class GetIdSchemasResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .depot.devtools.auth.v0.identity.admin.GetIdSchemasResponse.JsonSchema jsonschemas = 1[json_name = "jsonschemas"];</code>
     */
    private $jsonschemas;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Auth3\Identity\Admin\GetIdSchemasResponse\JsonSchema[]|\Google\Protobuf\Internal\RepeatedField $jsonschemas
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Devtools\Auth\V0\Proto\Identity\Admin\Admin::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .depot.devtools.auth.v0.identity.admin.GetIdSchemasResponse.JsonSchema jsonschemas = 1[json_name = "jsonschemas"];</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getJsonschemas()
    {
        return $this->jsonschemas;
    }

    /**
     * Generated from protobuf field <code>repeated .depot.devtools.auth.v0.identity.admin.GetIdSchemasResponse.JsonSchema jsonschemas = 1[json_name = "jsonschemas"];</code>
     * @param \Auth3\Identity\Admin\GetIdSchemasResponse\JsonSchema[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setJsonschemas($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Auth3\Identity\Admin\GetIdSchemasResponse\JsonSchema::class);
        $this->jsonschemas = $arr;

        return $this;
    }

}

