<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: identity/admin/admin.proto

namespace Auth3\Identity\Admin;

if (false) {
    /**
     * This class is deprecated. Use Auth3\Identity\Admin\GetIdentitiesByAttributeResponse\Identity instead.
     * @deprecated
     */
    class GetIdentitiesByAttributeResponse_Identity {}
}
class_exists(GetIdentitiesByAttributeResponse\Identity::class);
@trigger_error('Auth3\Identity\Admin\GetIdentitiesByAttributeResponse_Identity is deprecated and will be removed in the next major release. Use Auth3\Identity\Admin\GetIdentitiesByAttributeResponse\Identity instead', E_USER_DEPRECATED);

