<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: identity/admin/admin.proto

namespace Auth3\Identity\Admin;

if (false) {
    /**
     * This class is deprecated. Use Auth3\Identity\Admin\GetIdentityByIdentifierResponse\Identity\Lock instead.
     * @deprecated
     */
    class GetIdentityByIdentifierResponse_Identity_Lock {}
}
class_exists(GetIdentityByIdentifierResponse\Identity\Lock::class);
@trigger_error('Auth3\Identity\Admin\GetIdentityByIdentifierResponse_Identity_Lock is deprecated and will be removed in the next major release. Use Auth3\Identity\Admin\GetIdentityByIdentifierResponse\Identity\Lock instead', E_USER_DEPRECATED);

