<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: identity/admin/admin.proto

namespace Auth3\Identity\Admin;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>depot.devtools.auth.v0.identity.admin.GetIdentityLoginAttemptsResponse</code>
 */
class GetIdentityLoginAttemptsResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .depot.devtools.auth.v0.identity.admin.GetIdentityLoginAttemptsResponse.Attempt attempts = 1[json_name = "attempts"];</code>
     */
    private $attempts;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Auth3\Identity\Admin\GetIdentityLoginAttemptsResponse\Attempt[]|\Google\Protobuf\Internal\RepeatedField $attempts
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Devtools\Auth\V0\Proto\Identity\Admin\Admin::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .depot.devtools.auth.v0.identity.admin.GetIdentityLoginAttemptsResponse.Attempt attempts = 1[json_name = "attempts"];</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getAttempts()
    {
        return $this->attempts;
    }

    /**
     * Generated from protobuf field <code>repeated .depot.devtools.auth.v0.identity.admin.GetIdentityLoginAttemptsResponse.Attempt attempts = 1[json_name = "attempts"];</code>
     * @param \Auth3\Identity\Admin\GetIdentityLoginAttemptsResponse\Attempt[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setAttempts($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Auth3\Identity\Admin\GetIdentityLoginAttemptsResponse\Attempt::class);
        $this->attempts = $arr;

        return $this;
    }

}

