<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: identity/admin/admin.proto

namespace Auth3\Identity\Admin;

if (false) {
    /**
     * This class is deprecated. Use Auth3\Identity\Admin\GetIdSchemasResponse\JsonSchema instead.
     * @deprecated
     */
    class GetIdSchemasResponse_JsonSchema {}
}
class_exists(GetIdSchemasResponse\JsonSchema::class);
@trigger_error('Auth3\Identity\Admin\GetIdSchemasResponse_JsonSchema is deprecated and will be removed in the next major release. Use Auth3\Identity\Admin\GetIdSchemasResponse\JsonSchema instead', E_USER_DEPRECATED);

