<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: identity/admin/admin.proto

namespace Auth3\Identity\Admin;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>depot.devtools.auth.v0.identity.admin.GetIdentityByIdentifierResponse</code>
 */
class GetIdentityByIdentifierResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.depot.devtools.auth.v0.identity.admin.GetIdentityByIdentifierResponse.Identity identity = 1[json_name = "identity"];</code>
     */
    protected $identity = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Auth3\Identity\Admin\GetIdentityByIdentifierResponse\Identity $identity
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Devtools\Auth\V0\Proto\Identity\Admin\Admin::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.depot.devtools.auth.v0.identity.admin.GetIdentityByIdentifierResponse.Identity identity = 1[json_name = "identity"];</code>
     * @return \Auth3\Identity\Admin\GetIdentityByIdentifierResponse\Identity
     */
    public function getIdentity()
    {
        return $this->identity;
    }

    /**
     * Generated from protobuf field <code>.depot.devtools.auth.v0.identity.admin.GetIdentityByIdentifierResponse.Identity identity = 1[json_name = "identity"];</code>
     * @param \Auth3\Identity\Admin\GetIdentityByIdentifierResponse\Identity $var
     * @return $this
     */
    public function setIdentity($var)
    {
        GPBUtil::checkMessage($var, \Auth3\Identity\Admin\GetIdentityByIdentifierResponse\Identity::class);
        $this->identity = $var;

        return $this;
    }

}

