<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: identity/admin/admin.proto

namespace Auth3\Identity\Admin;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>depot.devtools.auth.v0.identity.admin.GetIdentitiesByAttributeResponse</code>
 */
class GetIdentitiesByAttributeResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .depot.devtools.auth.v0.identity.admin.GetIdentitiesByAttributeResponse.Identity identities = 1[json_name = "identities"];</code>
     */
    private $identities;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Auth3\Identity\Admin\GetIdentitiesByAttributeResponse\Identity[]|\Google\Protobuf\Internal\RepeatedField $identities
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Devtools\Auth\V0\Proto\Identity\Admin\Admin::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .depot.devtools.auth.v0.identity.admin.GetIdentitiesByAttributeResponse.Identity identities = 1[json_name = "identities"];</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getIdentities()
    {
        return $this->identities;
    }

    /**
     * Generated from protobuf field <code>repeated .depot.devtools.auth.v0.identity.admin.GetIdentitiesByAttributeResponse.Identity identities = 1[json_name = "identities"];</code>
     * @param \Auth3\Identity\Admin\GetIdentitiesByAttributeResponse\Identity[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setIdentities($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Auth3\Identity\Admin\GetIdentitiesByAttributeResponse\Identity::class);
        $this->identities = $arr;

        return $this;
    }

}

