<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: identity/admin/admin.proto

namespace Auth3\Identity\Admin;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>depot.devtools.auth.v0.identity.admin.GetIdentityByIdentifierRequest</code>
 */
class GetIdentityByIdentifierRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string attribute = 1[json_name = "attribute"];</code>
     */
    protected $attribute = '';
    /**
     * Generated from protobuf field <code>string value = 2[json_name = "value"];</code>
     */
    protected $value = '';
    /**
     * Generated from protobuf field <code>string connection_id = 3[json_name = "connectionId"];</code>
     */
    protected $connection_id = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $attribute
     *     @type string $value
     *     @type string $connection_id
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Devtools\Auth\V0\Proto\Identity\Admin\Admin::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string attribute = 1[json_name = "attribute"];</code>
     * @return string
     */
    public function getAttribute()
    {
        return $this->attribute;
    }

    /**
     * Generated from protobuf field <code>string attribute = 1[json_name = "attribute"];</code>
     * @param string $var
     * @return $this
     */
    public function setAttribute($var)
    {
        GPBUtil::checkString($var, True);
        $this->attribute = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string value = 2[json_name = "value"];</code>
     * @return string
     */
    public function getValue()
    {
        return $this->value;
    }

    /**
     * Generated from protobuf field <code>string value = 2[json_name = "value"];</code>
     * @param string $var
     * @return $this
     */
    public function setValue($var)
    {
        GPBUtil::checkString($var, True);
        $this->value = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string connection_id = 3[json_name = "connectionId"];</code>
     * @return string
     */
    public function getConnectionId()
    {
        return $this->connection_id;
    }

    /**
     * Generated from protobuf field <code>string connection_id = 3[json_name = "connectionId"];</code>
     * @param string $var
     * @return $this
     */
    public function setConnectionId($var)
    {
        GPBUtil::checkString($var, True);
        $this->connection_id = $var;

        return $this;
    }

}

