<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: identity/admin/admin.proto

namespace Auth3\Identity\Admin;

if (false) {
    /**
     * This class is deprecated. Use Auth3\Identity\Admin\GetIdentityLoginAttemptsResponse\Attempt instead.
     * @deprecated
     */
    class GetIdentityLoginAttemptsResponse_Attempt {}
}
class_exists(GetIdentityLoginAttemptsResponse\Attempt::class);
@trigger_error('Auth3\Identity\Admin\GetIdentityLoginAttemptsResponse_Attempt is deprecated and will be removed in the next major release. Use Auth3\Identity\Admin\GetIdentityLoginAttemptsResponse\Attempt instead', E_USER_DEPRECATED);

