<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: identity/admin/admin.proto

namespace Auth3\Identity\Admin;

if (false) {
    /**
     * This class is deprecated. Use Auth3\Identity\Admin\GetOAuth2ClientsResponse\Client instead.
     * @deprecated
     */
    class GetOAuth2ClientsResponse_Client {}
}
class_exists(GetOAuth2ClientsResponse\Client::class);
@trigger_error('Auth3\Identity\Admin\GetOAuth2ClientsResponse_Client is deprecated and will be removed in the next major release. Use Auth3\Identity\Admin\GetOAuth2ClientsResponse\Client instead', E_USER_DEPRECATED);

