<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: identity/admin/admin.proto

namespace Auth3\Identity\Admin;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>depot.devtools.auth.v0.identity.admin.GetOAuth2ClientsResponse</code>
 */
class GetOAuth2ClientsResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .depot.devtools.auth.v0.identity.admin.GetOAuth2ClientsResponse.Client clients = 1[json_name = "clients"];</code>
     */
    private $clients;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Auth3\Identity\Admin\GetOAuth2ClientsResponse\Client[]|\Google\Protobuf\Internal\RepeatedField $clients
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Devtools\Auth\V0\Proto\Identity\Admin\Admin::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .depot.devtools.auth.v0.identity.admin.GetOAuth2ClientsResponse.Client clients = 1[json_name = "clients"];</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getClients()
    {
        return $this->clients;
    }

    /**
     * Generated from protobuf field <code>repeated .depot.devtools.auth.v0.identity.admin.GetOAuth2ClientsResponse.Client clients = 1[json_name = "clients"];</code>
     * @param \Auth3\Identity\Admin\GetOAuth2ClientsResponse\Client[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setClients($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Auth3\Identity\Admin\GetOAuth2ClientsResponse\Client::class);
        $this->clients = $arr;

        return $this;
    }

}

