<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: identity/admin/admin.proto

namespace Auth3\Identity\Admin;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>depot.devtools.auth.v0.identity.admin.GetTraitsResponse</code>
 */
class GetTraitsResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string traits = 1[json_name = "traits"];</code>
     */
    protected $traits = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $traits
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Devtools\Auth\V0\Proto\Identity\Admin\Admin::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string traits = 1[json_name = "traits"];</code>
     * @return string
     */
    public function getTraits()
    {
        return $this->traits;
    }

    /**
     * Generated from protobuf field <code>string traits = 1[json_name = "traits"];</code>
     * @param string $var
     * @return $this
     */
    public function setTraits($var)
    {
        GPBUtil::checkString($var, True);
        $this->traits = $var;

        return $this;
    }

}

