<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: identity/admin/admin.proto

namespace Auth3\Identity\Admin;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>depot.devtools.auth.v0.identity.admin.GetUserBaseStatisticsResponse</code>
 */
class GetUserBaseStatisticsResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int32 total_users = 1[json_name = "totalUsers"];</code>
     */
    protected $total_users = 0;
    /**
     * Generated from protobuf field <code>map<string, int32> users_per_day = 2[json_name = "usersPerDay"];</code>
     */
    private $users_per_day;
    /**
     * Generated from protobuf field <code>map<string, int32> sessions_per_day = 3[json_name = "sessionsPerDay"];</code>
     */
    private $sessions_per_day;
    /**
     * Generated from protobuf field <code>int32 total_active_users = 4[json_name = "totalActiveUsers"];</code>
     */
    protected $total_active_users = 0;
    /**
     * Generated from protobuf field <code>double total_lifetime_used = 5[json_name = "totalLifetimeUsed"];</code>
     */
    protected $total_lifetime_used = 0.0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $total_users
     *     @type array|\Google\Protobuf\Internal\MapField $users_per_day
     *     @type array|\Google\Protobuf\Internal\MapField $sessions_per_day
     *     @type int $total_active_users
     *     @type float $total_lifetime_used
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Devtools\Auth\V0\Proto\Identity\Admin\Admin::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int32 total_users = 1[json_name = "totalUsers"];</code>
     * @return int
     */
    public function getTotalUsers()
    {
        return $this->total_users;
    }

    /**
     * Generated from protobuf field <code>int32 total_users = 1[json_name = "totalUsers"];</code>
     * @param int $var
     * @return $this
     */
    public function setTotalUsers($var)
    {
        GPBUtil::checkInt32($var);
        $this->total_users = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>map<string, int32> users_per_day = 2[json_name = "usersPerDay"];</code>
     * @return \Google\Protobuf\Internal\MapField
     */
    public function getUsersPerDay()
    {
        return $this->users_per_day;
    }

    /**
     * Generated from protobuf field <code>map<string, int32> users_per_day = 2[json_name = "usersPerDay"];</code>
     * @param array|\Google\Protobuf\Internal\MapField $var
     * @return $this
     */
    public function setUsersPerDay($var)
    {
        $arr = GPBUtil::checkMapField($var, \Google\Protobuf\Internal\GPBType::STRING, \Google\Protobuf\Internal\GPBType::INT32);
        $this->users_per_day = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>map<string, int32> sessions_per_day = 3[json_name = "sessionsPerDay"];</code>
     * @return \Google\Protobuf\Internal\MapField
     */
    public function getSessionsPerDay()
    {
        return $this->sessions_per_day;
    }

    /**
     * Generated from protobuf field <code>map<string, int32> sessions_per_day = 3[json_name = "sessionsPerDay"];</code>
     * @param array|\Google\Protobuf\Internal\MapField $var
     * @return $this
     */
    public function setSessionsPerDay($var)
    {
        $arr = GPBUtil::checkMapField($var, \Google\Protobuf\Internal\GPBType::STRING, \Google\Protobuf\Internal\GPBType::INT32);
        $this->sessions_per_day = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 total_active_users = 4[json_name = "totalActiveUsers"];</code>
     * @return int
     */
    public function getTotalActiveUsers()
    {
        return $this->total_active_users;
    }

    /**
     * Generated from protobuf field <code>int32 total_active_users = 4[json_name = "totalActiveUsers"];</code>
     * @param int $var
     * @return $this
     */
    public function setTotalActiveUsers($var)
    {
        GPBUtil::checkInt32($var);
        $this->total_active_users = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>double total_lifetime_used = 5[json_name = "totalLifetimeUsed"];</code>
     * @return float
     */
    public function getTotalLifetimeUsed()
    {
        return $this->total_lifetime_used;
    }

    /**
     * Generated from protobuf field <code>double total_lifetime_used = 5[json_name = "totalLifetimeUsed"];</code>
     * @param float $var
     * @return $this
     */
    public function setTotalLifetimeUsed($var)
    {
        GPBUtil::checkDouble($var);
        $this->total_lifetime_used = $var;

        return $this;
    }

}

