<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: identity/admin/admin.proto

namespace Auth3\Identity\Admin;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>depot.devtools.auth.v0.identity.admin.GetUserBaseStatisticsRequest</code>
 */
class GetUserBaseStatisticsRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>uint32 days_before = 1[json_name = "daysBefore"];</code>
     */
    protected $days_before = 0;
    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp lifetime_start_at = 2[json_name = "lifetimeStartAt"];</code>
     */
    protected $lifetime_start_at = null;
    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp lifetime_end_at = 3[json_name = "lifetimeEndAt"];</code>
     */
    protected $lifetime_end_at = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $days_before
     *     @type \Google\Protobuf\Timestamp $lifetime_start_at
     *     @type \Google\Protobuf\Timestamp $lifetime_end_at
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Devtools\Auth\V0\Proto\Identity\Admin\Admin::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>uint32 days_before = 1[json_name = "daysBefore"];</code>
     * @return int
     */
    public function getDaysBefore()
    {
        return $this->days_before;
    }

    /**
     * Generated from protobuf field <code>uint32 days_before = 1[json_name = "daysBefore"];</code>
     * @param int $var
     * @return $this
     */
    public function setDaysBefore($var)
    {
        GPBUtil::checkUint32($var);
        $this->days_before = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp lifetime_start_at = 2[json_name = "lifetimeStartAt"];</code>
     * @return \Google\Protobuf\Timestamp
     */
    public function getLifetimeStartAt()
    {
        return $this->lifetime_start_at;
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp lifetime_start_at = 2[json_name = "lifetimeStartAt"];</code>
     * @param \Google\Protobuf\Timestamp $var
     * @return $this
     */
    public function setLifetimeStartAt($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Timestamp::class);
        $this->lifetime_start_at = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp lifetime_end_at = 3[json_name = "lifetimeEndAt"];</code>
     * @return \Google\Protobuf\Timestamp
     */
    public function getLifetimeEndAt()
    {
        return $this->lifetime_end_at;
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp lifetime_end_at = 3[json_name = "lifetimeEndAt"];</code>
     * @param \Google\Protobuf\Timestamp $var
     * @return $this
     */
    public function setLifetimeEndAt($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Timestamp::class);
        $this->lifetime_end_at = $var;

        return $this;
    }

}

