<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: identity/admin/admin.proto

namespace Auth3\Identity\Admin;

use UnexpectedValueException;

/**
 * Protobuf type <code>depot.devtools.auth.v0.identity.admin.GrantType</code>
 */
class GrantType
{
    /**
     * Generated from protobuf enum <code>GRANT_TYPE_UNSET = 0;</code>
     */
    const GRANT_TYPE_UNSET = 0;
    /**
     * Generated from protobuf enum <code>GRANT_TYPE_CLIENT_CREDENTIALS = 1;</code>
     */
    const GRANT_TYPE_CLIENT_CREDENTIALS = 1;
    /**
     * Generated from protobuf enum <code>GRANT_TYPE_AUTHORIZATION_CODE = 2;</code>
     */
    const GRANT_TYPE_AUTHORIZATION_CODE = 2;
    /**
     * Generated from protobuf enum <code>GRANT_TYPE_IMPLICIT = 3;</code>
     */
    const GRANT_TYPE_IMPLICIT = 3;
    /**
     * Generated from protobuf enum <code>GRANT_TYPE_REFRESH_TOKEN = 4;</code>
     */
    const GRANT_TYPE_REFRESH_TOKEN = 4;
    /**
     * Generated from protobuf enum <code>GRANT_TYPE_DEVICE_CODE = 5;</code>
     */
    const GRANT_TYPE_DEVICE_CODE = 5;

    private static $valueToName = [
        self::GRANT_TYPE_UNSET => 'GRANT_TYPE_UNSET',
        self::GRANT_TYPE_CLIENT_CREDENTIALS => 'GRANT_TYPE_CLIENT_CREDENTIALS',
        self::GRANT_TYPE_AUTHORIZATION_CODE => 'GRANT_TYPE_AUTHORIZATION_CODE',
        self::GRANT_TYPE_IMPLICIT => 'GRANT_TYPE_IMPLICIT',
        self::GRANT_TYPE_REFRESH_TOKEN => 'GRANT_TYPE_REFRESH_TOKEN',
        self::GRANT_TYPE_DEVICE_CODE => 'GRANT_TYPE_DEVICE_CODE',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

