<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: identity/admin/admin.proto

namespace Auth3\Identity\Admin;

use UnexpectedValueException;

/**
 * Protobuf type <code>depot.devtools.auth.v0.identity.admin.ResponseType</code>
 */
class ResponseType
{
    /**
     * Generated from protobuf enum <code>RESPONSE_TYPE_UNSET = 0;</code>
     */
    const RESPONSE_TYPE_UNSET = 0;
    /**
     * Generated from protobuf enum <code>RESPONSE_TYPE_NONE = 1;</code>
     */
    const RESPONSE_TYPE_NONE = 1;
    /**
     * Generated from protobuf enum <code>RESPONSE_TYPE_ID_TOKEN = 2;</code>
     */
    const RESPONSE_TYPE_ID_TOKEN = 2;
    /**
     * Generated from protobuf enum <code>RESPONSE_TYPE_TOKEN = 3;</code>
     */
    const RESPONSE_TYPE_TOKEN = 3;
    /**
     * Generated from protobuf enum <code>RESPONSE_TYPE_CODE = 4;</code>
     */
    const RESPONSE_TYPE_CODE = 4;
    /**
     * Generated from protobuf enum <code>RESPONSE_TYPE_ID_TOKEN_TOKEN = 5;</code>
     */
    const RESPONSE_TYPE_ID_TOKEN_TOKEN = 5;
    /**
     * Generated from protobuf enum <code>RESPONSE_TYPE_CODE_ID_TOKEN = 6;</code>
     */
    const RESPONSE_TYPE_CODE_ID_TOKEN = 6;
    /**
     * Generated from protobuf enum <code>RESPONSE_TYPE_CODE_TOKEN = 7;</code>
     */
    const RESPONSE_TYPE_CODE_TOKEN = 7;
    /**
     * Generated from protobuf enum <code>RESPONSE_TYPE_CODE_ID_TOKEN_TOKEN = 8;</code>
     */
    const RESPONSE_TYPE_CODE_ID_TOKEN_TOKEN = 8;

    private static $valueToName = [
        self::RESPONSE_TYPE_UNSET => 'RESPONSE_TYPE_UNSET',
        self::RESPONSE_TYPE_NONE => 'RESPONSE_TYPE_NONE',
        self::RESPONSE_TYPE_ID_TOKEN => 'RESPONSE_TYPE_ID_TOKEN',
        self::RESPONSE_TYPE_TOKEN => 'RESPONSE_TYPE_TOKEN',
        self::RESPONSE_TYPE_CODE => 'RESPONSE_TYPE_CODE',
        self::RESPONSE_TYPE_ID_TOKEN_TOKEN => 'RESPONSE_TYPE_ID_TOKEN_TOKEN',
        self::RESPONSE_TYPE_CODE_ID_TOKEN => 'RESPONSE_TYPE_CODE_ID_TOKEN',
        self::RESPONSE_TYPE_CODE_TOKEN => 'RESPONSE_TYPE_CODE_TOKEN',
        self::RESPONSE_TYPE_CODE_ID_TOKEN_TOKEN => 'RESPONSE_TYPE_CODE_ID_TOKEN_TOKEN',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

