<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: identity/admin/admin.proto

namespace Auth3\Identity\Admin;

use UnexpectedValueException;

/**
 * Protobuf type <code>depot.devtools.auth.v0.identity.admin.TokenEndpointAuthMethod</code>
 */
class TokenEndpointAuthMethod
{
    /**
     * Generated from protobuf enum <code>TOKEN_ENDPOINT_AUTH_METHOD_CLIENT_SECRET_BASIC = 0;</code>
     */
    const TOKEN_ENDPOINT_AUTH_METHOD_CLIENT_SECRET_BASIC = 0;
    /**
     * Generated from protobuf enum <code>TOKEN_ENDPOINT_AUTH_METHOD_CLIENT_SECRET_POST = 1;</code>
     */
    const TOKEN_ENDPOINT_AUTH_METHOD_CLIENT_SECRET_POST = 1;
    /**
     * Generated from protobuf enum <code>TOKEN_ENDPOINT_AUTH_METHOD_PRIVATE_KEY_JWT = 2;</code>
     */
    const TOKEN_ENDPOINT_AUTH_METHOD_PRIVATE_KEY_JWT = 2;
    /**
     * Generated from protobuf enum <code>TOKEN_ENDPOINT_AUTH_METHOD_NONE = 3;</code>
     */
    const TOKEN_ENDPOINT_AUTH_METHOD_NONE = 3;

    private static $valueToName = [
        self::TOKEN_ENDPOINT_AUTH_METHOD_CLIENT_SECRET_BASIC => 'TOKEN_ENDPOINT_AUTH_METHOD_CLIENT_SECRET_BASIC',
        self::TOKEN_ENDPOINT_AUTH_METHOD_CLIENT_SECRET_POST => 'TOKEN_ENDPOINT_AUTH_METHOD_CLIENT_SECRET_POST',
        self::TOKEN_ENDPOINT_AUTH_METHOD_PRIVATE_KEY_JWT => 'TOKEN_ENDPOINT_AUTH_METHOD_PRIVATE_KEY_JWT',
        self::TOKEN_ENDPOINT_AUTH_METHOD_NONE => 'TOKEN_ENDPOINT_AUTH_METHOD_NONE',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

