<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: identity/admin/admin.proto

namespace Auth3\Identity\Admin;

use UnexpectedValueException;

/**
 * Protobuf type <code>depot.devtools.auth.v0.identity.admin.TokenEndpointAuthSigningAlg</code>
 */
class TokenEndpointAuthSigningAlg
{
    /**
     * Generated from protobuf enum <code>TOKEN_ENDPOINT_AUTH_SIGNING_ALG_UNSET = 0;</code>
     */
    const TOKEN_ENDPOINT_AUTH_SIGNING_ALG_UNSET = 0;
    /**
     * Generated from protobuf enum <code>TOKEN_ENDPOINT_AUTH_SIGNING_ALG_RS256 = 1;</code>
     */
    const TOKEN_ENDPOINT_AUTH_SIGNING_ALG_RS256 = 1;
    /**
     * Generated from protobuf enum <code>TOKEN_ENDPOINT_AUTH_SIGNING_ALG_RS384 = 2;</code>
     */
    const TOKEN_ENDPOINT_AUTH_SIGNING_ALG_RS384 = 2;
    /**
     * Generated from protobuf enum <code>TOKEN_ENDPOINT_AUTH_SIGNING_ALG_RS512 = 3;</code>
     */
    const TOKEN_ENDPOINT_AUTH_SIGNING_ALG_RS512 = 3;
    /**
     * Generated from protobuf enum <code>TOKEN_ENDPOINT_AUTH_SIGNING_ALG_PS256 = 4;</code>
     */
    const TOKEN_ENDPOINT_AUTH_SIGNING_ALG_PS256 = 4;
    /**
     * Generated from protobuf enum <code>TOKEN_ENDPOINT_AUTH_SIGNING_ALG_PS384 = 5;</code>
     */
    const TOKEN_ENDPOINT_AUTH_SIGNING_ALG_PS384 = 5;
    /**
     * Generated from protobuf enum <code>TOKEN_ENDPOINT_AUTH_SIGNING_ALG_PS512 = 6;</code>
     */
    const TOKEN_ENDPOINT_AUTH_SIGNING_ALG_PS512 = 6;
    /**
     * Generated from protobuf enum <code>TOKEN_ENDPOINT_AUTH_SIGNING_ALG_ES256 = 7;</code>
     */
    const TOKEN_ENDPOINT_AUTH_SIGNING_ALG_ES256 = 7;
    /**
     * Generated from protobuf enum <code>TOKEN_ENDPOINT_AUTH_SIGNING_ALG_ES384 = 8;</code>
     */
    const TOKEN_ENDPOINT_AUTH_SIGNING_ALG_ES384 = 8;
    /**
     * Generated from protobuf enum <code>TOKEN_ENDPOINT_AUTH_SIGNING_ALG_ES512 = 9;</code>
     */
    const TOKEN_ENDPOINT_AUTH_SIGNING_ALG_ES512 = 9;

    private static $valueToName = [
        self::TOKEN_ENDPOINT_AUTH_SIGNING_ALG_UNSET => 'TOKEN_ENDPOINT_AUTH_SIGNING_ALG_UNSET',
        self::TOKEN_ENDPOINT_AUTH_SIGNING_ALG_RS256 => 'TOKEN_ENDPOINT_AUTH_SIGNING_ALG_RS256',
        self::TOKEN_ENDPOINT_AUTH_SIGNING_ALG_RS384 => 'TOKEN_ENDPOINT_AUTH_SIGNING_ALG_RS384',
        self::TOKEN_ENDPOINT_AUTH_SIGNING_ALG_RS512 => 'TOKEN_ENDPOINT_AUTH_SIGNING_ALG_RS512',
        self::TOKEN_ENDPOINT_AUTH_SIGNING_ALG_PS256 => 'TOKEN_ENDPOINT_AUTH_SIGNING_ALG_PS256',
        self::TOKEN_ENDPOINT_AUTH_SIGNING_ALG_PS384 => 'TOKEN_ENDPOINT_AUTH_SIGNING_ALG_PS384',
        self::TOKEN_ENDPOINT_AUTH_SIGNING_ALG_PS512 => 'TOKEN_ENDPOINT_AUTH_SIGNING_ALG_PS512',
        self::TOKEN_ENDPOINT_AUTH_SIGNING_ALG_ES256 => 'TOKEN_ENDPOINT_AUTH_SIGNING_ALG_ES256',
        self::TOKEN_ENDPOINT_AUTH_SIGNING_ALG_ES384 => 'TOKEN_ENDPOINT_AUTH_SIGNING_ALG_ES384',
        self::TOKEN_ENDPOINT_AUTH_SIGNING_ALG_ES512 => 'TOKEN_ENDPOINT_AUTH_SIGNING_ALG_ES512',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

