<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: identity/admin/admin.proto

namespace Auth3\Identity\Admin;

if (false) {
    /**
     * This class is deprecated. Use Auth3\Identity\Admin\UpdateEmailsSetupRequest\EmailTemplate instead.
     * @deprecated
     */
    class UpdateEmailsSetupRequest_EmailTemplate {}
}
class_exists(UpdateEmailsSetupRequest\EmailTemplate::class);
@trigger_error('Auth3\Identity\Admin\UpdateEmailsSetupRequest_EmailTemplate is deprecated and will be removed in the next major release. Use Auth3\Identity\Admin\UpdateEmailsSetupRequest\EmailTemplate instead', E_USER_DEPRECATED);

