<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: identity/admin/admin.proto

namespace Auth3\Identity\Admin;

if (false) {
    /**
     * This class is deprecated. Use Auth3\Identity\Admin\UpdateConnectionRequest\Types instead.
     * @deprecated
     */
    class UpdateConnectionRequest_Types {}
}
class_exists(UpdateConnectionRequest\Types::class);
@trigger_error('Auth3\Identity\Admin\UpdateConnectionRequest_Types is deprecated and will be removed in the next major release. Use Auth3\Identity\Admin\UpdateConnectionRequest\Types instead', E_USER_DEPRECATED);

