<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: identity/admin/admin.proto

namespace Auth3\Identity\Admin;

if (false) {
    /**
     * This class is deprecated. Use Auth3\Identity\Admin\UpdateIdentityRequest\Lock instead.
     * @deprecated
     */
    class UpdateIdentityRequest_Lock {}
}
class_exists(UpdateIdentityRequest\Lock::class);
@trigger_error('Auth3\Identity\Admin\UpdateIdentityRequest_Lock is deprecated and will be removed in the next major release. Use Auth3\Identity\Admin\UpdateIdentityRequest\Lock instead', E_USER_DEPRECATED);

