<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: identity/admin/admin.proto

namespace Auth3\Identity\Admin;

if (false) {
    /**
     * This class is deprecated. Use Auth3\Identity\Admin\UpdateEmailsSetupRequest\EmailSender instead.
     * @deprecated
     */
    class UpdateEmailsSetupRequest_EmailSender {}
}
class_exists(UpdateEmailsSetupRequest\EmailSender::class);
@trigger_error('Auth3\Identity\Admin\UpdateEmailsSetupRequest_EmailSender is deprecated and will be removed in the next major release. Use Auth3\Identity\Admin\UpdateEmailsSetupRequest\EmailSender instead', E_USER_DEPRECATED);

