<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: identity/admin/admin.proto

namespace Auth3\Identity\Admin;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>depot.devtools.auth.v0.identity.admin.UpdateIdentityRequest</code>
 */
class UpdateIdentityRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string identity_id = 1[json_name = "identityId"];</code>
     */
    protected $identity_id = '';
    /**
     * Generated from protobuf field <code>.depot.devtools.auth.v0.identity.admin.UpdateIdentityRequest.Lock lock = 2[json_name = "lock"];</code>
     */
    protected $lock = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $identity_id
     *     @type int $lock
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Devtools\Auth\V0\Proto\Identity\Admin\Admin::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string identity_id = 1[json_name = "identityId"];</code>
     * @return string
     */
    public function getIdentityId()
    {
        return $this->identity_id;
    }

    /**
     * Generated from protobuf field <code>string identity_id = 1[json_name = "identityId"];</code>
     * @param string $var
     * @return $this
     */
    public function setIdentityId($var)
    {
        GPBUtil::checkString($var, True);
        $this->identity_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.depot.devtools.auth.v0.identity.admin.UpdateIdentityRequest.Lock lock = 2[json_name = "lock"];</code>
     * @return int
     */
    public function getLock()
    {
        return $this->lock;
    }

    /**
     * Generated from protobuf field <code>.depot.devtools.auth.v0.identity.admin.UpdateIdentityRequest.Lock lock = 2[json_name = "lock"];</code>
     * @param int $var
     * @return $this
     */
    public function setLock($var)
    {
        GPBUtil::checkEnum($var, \Auth3\Identity\Admin\UpdateIdentityRequest\Lock::class);
        $this->lock = $var;

        return $this;
    }

}

