<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: identity/admin/admin.proto

namespace Auth3\Identity\Admin;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>depot.devtools.auth.v0.identity.admin.UpdateEmailsSetupRequest</code>
 */
class UpdateEmailsSetupRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.depot.devtools.auth.v0.identity.admin.UpdateEmailsSetupRequest.EmailTemplate welcome = 1[json_name = "welcome"];</code>
     */
    protected $welcome = null;
    /**
     * Generated from protobuf field <code>.depot.devtools.auth.v0.identity.admin.UpdateEmailsSetupRequest.EmailTemplate account_verification = 2[json_name = "accountVerification"];</code>
     */
    protected $account_verification = null;
    /**
     * Generated from protobuf field <code>.depot.devtools.auth.v0.identity.admin.UpdateEmailsSetupRequest.EmailTemplate account_recovery = 3[json_name = "accountRecovery"];</code>
     */
    protected $account_recovery = null;
    /**
     * Generated from protobuf field <code>.depot.devtools.auth.v0.identity.admin.UpdateEmailsSetupRequest.EmailTemplate account_recovered = 4[json_name = "accountRecovered"];</code>
     */
    protected $account_recovered = null;
    /**
     * Generated from protobuf field <code>.depot.devtools.auth.v0.identity.admin.UpdateEmailsSetupRequest.EmailTemplate otp = 5[json_name = "otp"];</code>
     */
    protected $otp = null;
    /**
     * Generated from protobuf field <code>.depot.devtools.auth.v0.identity.admin.UpdateEmailsSetupRequest.EmailSender smtp = 6[json_name = "smtp"];</code>
     */
    protected $smtp = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Auth3\Identity\Admin\UpdateEmailsSetupRequest\EmailTemplate $welcome
     *     @type \Auth3\Identity\Admin\UpdateEmailsSetupRequest\EmailTemplate $account_verification
     *     @type \Auth3\Identity\Admin\UpdateEmailsSetupRequest\EmailTemplate $account_recovery
     *     @type \Auth3\Identity\Admin\UpdateEmailsSetupRequest\EmailTemplate $account_recovered
     *     @type \Auth3\Identity\Admin\UpdateEmailsSetupRequest\EmailTemplate $otp
     *     @type \Auth3\Identity\Admin\UpdateEmailsSetupRequest\EmailSender $smtp
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Devtools\Auth\V0\Proto\Identity\Admin\Admin::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.depot.devtools.auth.v0.identity.admin.UpdateEmailsSetupRequest.EmailTemplate welcome = 1[json_name = "welcome"];</code>
     * @return \Auth3\Identity\Admin\UpdateEmailsSetupRequest\EmailTemplate
     */
    public function getWelcome()
    {
        return $this->welcome;
    }

    /**
     * Generated from protobuf field <code>.depot.devtools.auth.v0.identity.admin.UpdateEmailsSetupRequest.EmailTemplate welcome = 1[json_name = "welcome"];</code>
     * @param \Auth3\Identity\Admin\UpdateEmailsSetupRequest\EmailTemplate $var
     * @return $this
     */
    public function setWelcome($var)
    {
        GPBUtil::checkMessage($var, \Auth3\Identity\Admin\UpdateEmailsSetupRequest\EmailTemplate::class);
        $this->welcome = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.depot.devtools.auth.v0.identity.admin.UpdateEmailsSetupRequest.EmailTemplate account_verification = 2[json_name = "accountVerification"];</code>
     * @return \Auth3\Identity\Admin\UpdateEmailsSetupRequest\EmailTemplate
     */
    public function getAccountVerification()
    {
        return $this->account_verification;
    }

    /**
     * Generated from protobuf field <code>.depot.devtools.auth.v0.identity.admin.UpdateEmailsSetupRequest.EmailTemplate account_verification = 2[json_name = "accountVerification"];</code>
     * @param \Auth3\Identity\Admin\UpdateEmailsSetupRequest\EmailTemplate $var
     * @return $this
     */
    public function setAccountVerification($var)
    {
        GPBUtil::checkMessage($var, \Auth3\Identity\Admin\UpdateEmailsSetupRequest\EmailTemplate::class);
        $this->account_verification = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.depot.devtools.auth.v0.identity.admin.UpdateEmailsSetupRequest.EmailTemplate account_recovery = 3[json_name = "accountRecovery"];</code>
     * @return \Auth3\Identity\Admin\UpdateEmailsSetupRequest\EmailTemplate
     */
    public function getAccountRecovery()
    {
        return $this->account_recovery;
    }

    /**
     * Generated from protobuf field <code>.depot.devtools.auth.v0.identity.admin.UpdateEmailsSetupRequest.EmailTemplate account_recovery = 3[json_name = "accountRecovery"];</code>
     * @param \Auth3\Identity\Admin\UpdateEmailsSetupRequest\EmailTemplate $var
     * @return $this
     */
    public function setAccountRecovery($var)
    {
        GPBUtil::checkMessage($var, \Auth3\Identity\Admin\UpdateEmailsSetupRequest\EmailTemplate::class);
        $this->account_recovery = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.depot.devtools.auth.v0.identity.admin.UpdateEmailsSetupRequest.EmailTemplate account_recovered = 4[json_name = "accountRecovered"];</code>
     * @return \Auth3\Identity\Admin\UpdateEmailsSetupRequest\EmailTemplate
     */
    public function getAccountRecovered()
    {
        return $this->account_recovered;
    }

    /**
     * Generated from protobuf field <code>.depot.devtools.auth.v0.identity.admin.UpdateEmailsSetupRequest.EmailTemplate account_recovered = 4[json_name = "accountRecovered"];</code>
     * @param \Auth3\Identity\Admin\UpdateEmailsSetupRequest\EmailTemplate $var
     * @return $this
     */
    public function setAccountRecovered($var)
    {
        GPBUtil::checkMessage($var, \Auth3\Identity\Admin\UpdateEmailsSetupRequest\EmailTemplate::class);
        $this->account_recovered = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.depot.devtools.auth.v0.identity.admin.UpdateEmailsSetupRequest.EmailTemplate otp = 5[json_name = "otp"];</code>
     * @return \Auth3\Identity\Admin\UpdateEmailsSetupRequest\EmailTemplate
     */
    public function getOtp()
    {
        return $this->otp;
    }

    /**
     * Generated from protobuf field <code>.depot.devtools.auth.v0.identity.admin.UpdateEmailsSetupRequest.EmailTemplate otp = 5[json_name = "otp"];</code>
     * @param \Auth3\Identity\Admin\UpdateEmailsSetupRequest\EmailTemplate $var
     * @return $this
     */
    public function setOtp($var)
    {
        GPBUtil::checkMessage($var, \Auth3\Identity\Admin\UpdateEmailsSetupRequest\EmailTemplate::class);
        $this->otp = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.depot.devtools.auth.v0.identity.admin.UpdateEmailsSetupRequest.EmailSender smtp = 6[json_name = "smtp"];</code>
     * @return \Auth3\Identity\Admin\UpdateEmailsSetupRequest\EmailSender
     */
    public function getSmtp()
    {
        return $this->smtp;
    }

    /**
     * Generated from protobuf field <code>.depot.devtools.auth.v0.identity.admin.UpdateEmailsSetupRequest.EmailSender smtp = 6[json_name = "smtp"];</code>
     * @param \Auth3\Identity\Admin\UpdateEmailsSetupRequest\EmailSender $var
     * @return $this
     */
    public function setSmtp($var)
    {
        GPBUtil::checkMessage($var, \Auth3\Identity\Admin\UpdateEmailsSetupRequest\EmailSender::class);
        $this->smtp = $var;

        return $this;
    }

}

