<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: identity/admin/admin.proto

namespace Auth3\Identity\Admin\CreateConnectionRequest;

use UnexpectedValueException;

/**
 * Protobuf type <code>depot.devtools.auth.v0.identity.admin.CreateConnectionRequest.Providers</code>
 */
class Providers
{
    /**
     * Generated from protobuf enum <code>NONE = 0;</code>
     */
    const NONE = 0;
    /**
     * Generated from protobuf enum <code>OPENID = 1;</code>
     */
    const OPENID = 1;
    /**
     * Generated from protobuf enum <code>AMAZON = 2;</code>
     */
    const AMAZON = 2;
    /**
     * Generated from protobuf enum <code>BITBUCKET = 3;</code>
     */
    const BITBUCKET = 3;
    /**
     * Generated from protobuf enum <code>BOX = 4;</code>
     */
    const BOX = 4;
    /**
     * Generated from protobuf enum <code>DAILYMOTION = 5;</code>
     */
    const DAILYMOTION = 5;
    /**
     * Generated from protobuf enum <code>DEEZER = 6;</code>
     */
    const DEEZER = 6;
    /**
     * Generated from protobuf enum <code>DIGITALOCEAN = 7;</code>
     */
    const DIGITALOCEAN = 7;
    /**
     * Generated from protobuf enum <code>DISCORD = 8;</code>
     */
    const DISCORD = 8;
    /**
     * Generated from protobuf enum <code>DROPBOX = 9;</code>
     */
    const DROPBOX = 9;
    /**
     * Generated from protobuf enum <code>EVEONLINE = 10;</code>
     */
    const EVEONLINE = 10;
    /**
     * Generated from protobuf enum <code>FACEBOOK = 11;</code>
     */
    const FACEBOOK = 11;
    /**
     * Generated from protobuf enum <code>FITBIT = 12;</code>
     */
    const FITBIT = 12;
    /**
     * Generated from protobuf enum <code>GITEA = 13;</code>
     */
    const GITEA = 13;
    /**
     * Generated from protobuf enum <code>GITHUB = 14;</code>
     */
    const GITHUB = 14;
    /**
     * Generated from protobuf enum <code>GITLAB = 15;</code>
     */
    const GITLAB = 15;
    /**
     * Generated from protobuf enum <code>GOOGLE = 16;</code>
     */
    const GOOGLE = 16;
    /**
     * Generated from protobuf enum <code>SHOPIFY = 18;</code>
     */
    const SHOPIFY = 18;
    /**
     * Generated from protobuf enum <code>SOUNDCLOUD = 19;</code>
     */
    const SOUNDCLOUD = 19;
    /**
     * Generated from protobuf enum <code>SPOTIFY = 20;</code>
     */
    const SPOTIFY = 20;
    /**
     * Generated from protobuf enum <code>STEAM = 21;</code>
     */
    const STEAM = 21;
    /**
     * Generated from protobuf enum <code>STRIPE = 22;</code>
     */
    const STRIPE = 22;
    /**
     * Generated from protobuf enum <code>TWITCH = 23;</code>
     */
    const TWITCH = 23;
    /**
     * Generated from protobuf enum <code>UBER = 24;</code>
     */
    const UBER = 24;
    /**
     * Generated from protobuf enum <code>WEPAY = 25;</code>
     */
    const WEPAY = 25;
    /**
     * Generated from protobuf enum <code>YAHOO = 26;</code>
     */
    const YAHOO = 26;
    /**
     * Generated from protobuf enum <code>YAMMER = 27;</code>
     */
    const YAMMER = 27;
    /**
     * Generated from protobuf enum <code>HEROKU = 28;</code>
     */
    const HEROKU = 28;
    /**
     * Generated from protobuf enum <code>INSTAGRAM = 29;</code>
     */
    const INSTAGRAM = 29;
    /**
     * Generated from protobuf enum <code>INTERCOM = 30;</code>
     */
    const INTERCOM = 30;
    /**
     * Generated from protobuf enum <code>KAKAO = 31;</code>
     */
    const KAKAO = 31;
    /**
     * Generated from protobuf enum <code>LASTFM = 32;</code>
     */
    const LASTFM = 32;
    /**
     * Generated from protobuf enum <code>LINKEDIN = 33;</code>
     */
    const LINKEDIN = 33;
    /**
     * Generated from protobuf enum <code>LINE = 34;</code>
     */
    const LINE = 34;
    /**
     * Generated from protobuf enum <code>ONEDRIVE = 35;</code>
     */
    const ONEDRIVE = 35;
    /**
     * Generated from protobuf enum <code>AZUREAD = 36;</code>
     */
    const AZUREAD = 36;
    /**
     * Generated from protobuf enum <code>MICROSOFTONLINE = 37;</code>
     */
    const MICROSOFTONLINE = 37;
    /**
     * Generated from protobuf enum <code>BATTLENET = 38;</code>
     */
    const BATTLENET = 38;
    /**
     * Generated from protobuf enum <code>PAYPAL = 39;</code>
     */
    const PAYPAL = 39;
    /**
     * Generated from protobuf enum <code>TWITTER = 40;</code>
     */
    const TWITTER = 40;
    /**
     * Generated from protobuf enum <code>SALESFORCE = 41;</code>
     */
    const SALESFORCE = 41;
    /**
     * Generated from protobuf enum <code>TYPETALK = 42;</code>
     */
    const TYPETALK = 42;
    /**
     * Generated from protobuf enum <code>SLACK = 43;</code>
     */
    const SLACK = 43;
    /**
     * Generated from protobuf enum <code>MEETUP = 44;</code>
     */
    const MEETUP = 44;
    /**
     * Generated from protobuf enum <code>XERO = 46;</code>
     */
    const XERO = 46;
    /**
     * Generated from protobuf enum <code>VK = 47;</code>
     */
    const VK = 47;
    /**
     * Generated from protobuf enum <code>NAVER = 48;</code>
     */
    const NAVER = 48;
    /**
     * Generated from protobuf enum <code>YANDEX = 49;</code>
     */
    const YANDEX = 49;
    /**
     * Generated from protobuf enum <code>NEXTCLOUD = 50;</code>
     */
    const NEXTCLOUD = 50;
    /**
     * Generated from protobuf enum <code>APPLE = 52;</code>
     */
    const APPLE = 52;
    /**
     * Generated from protobuf enum <code>STRAVA = 53;</code>
     */
    const STRAVA = 53;

    private static $valueToName = [
        self::NONE => 'NONE',
        self::OPENID => 'OPENID',
        self::AMAZON => 'AMAZON',
        self::BITBUCKET => 'BITBUCKET',
        self::BOX => 'BOX',
        self::DAILYMOTION => 'DAILYMOTION',
        self::DEEZER => 'DEEZER',
        self::DIGITALOCEAN => 'DIGITALOCEAN',
        self::DISCORD => 'DISCORD',
        self::DROPBOX => 'DROPBOX',
        self::EVEONLINE => 'EVEONLINE',
        self::FACEBOOK => 'FACEBOOK',
        self::FITBIT => 'FITBIT',
        self::GITEA => 'GITEA',
        self::GITHUB => 'GITHUB',
        self::GITLAB => 'GITLAB',
        self::GOOGLE => 'GOOGLE',
        self::SHOPIFY => 'SHOPIFY',
        self::SOUNDCLOUD => 'SOUNDCLOUD',
        self::SPOTIFY => 'SPOTIFY',
        self::STEAM => 'STEAM',
        self::STRIPE => 'STRIPE',
        self::TWITCH => 'TWITCH',
        self::UBER => 'UBER',
        self::WEPAY => 'WEPAY',
        self::YAHOO => 'YAHOO',
        self::YAMMER => 'YAMMER',
        self::HEROKU => 'HEROKU',
        self::INSTAGRAM => 'INSTAGRAM',
        self::INTERCOM => 'INTERCOM',
        self::KAKAO => 'KAKAO',
        self::LASTFM => 'LASTFM',
        self::LINKEDIN => 'LINKEDIN',
        self::LINE => 'LINE',
        self::ONEDRIVE => 'ONEDRIVE',
        self::AZUREAD => 'AZUREAD',
        self::MICROSOFTONLINE => 'MICROSOFTONLINE',
        self::BATTLENET => 'BATTLENET',
        self::PAYPAL => 'PAYPAL',
        self::TWITTER => 'TWITTER',
        self::SALESFORCE => 'SALESFORCE',
        self::TYPETALK => 'TYPETALK',
        self::SLACK => 'SLACK',
        self::MEETUP => 'MEETUP',
        self::XERO => 'XERO',
        self::VK => 'VK',
        self::NAVER => 'NAVER',
        self::YANDEX => 'YANDEX',
        self::NEXTCLOUD => 'NEXTCLOUD',
        self::APPLE => 'APPLE',
        self::STRAVA => 'STRAVA',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(Providers::class, \Auth3\Identity\Admin\CreateConnectionRequest_Providers::class);

