<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: identity/admin/admin.proto

namespace Auth3\Identity\Admin\GetIdentitiesResponse;

use UnexpectedValueException;

/**
 * Protobuf type <code>depot.devtools.auth.v0.identity.admin.GetIdentitiesResponse.Lock</code>
 */
class Lock
{
    /**
     * Generated from protobuf enum <code>UNLOCKED = 0;</code>
     */
    const UNLOCKED = 0;
    /**
     * Generated from protobuf enum <code>ADMIN_LOCKED = 1;</code>
     */
    const ADMIN_LOCKED = 1;

    private static $valueToName = [
        self::UNLOCKED => 'UNLOCKED',
        self::ADMIN_LOCKED => 'ADMIN_LOCKED',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(Lock::class, \Auth3\Identity\Admin\GetIdentitiesResponse_Lock::class);

