<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: identity/admin/admin.proto

namespace Auth3\Identity\Admin\GetIdentityLoginAttemptsResponse;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>depot.devtools.auth.v0.identity.admin.GetIdentityLoginAttemptsResponse.Attempt</code>
 */
class Attempt extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string id = 1[json_name = "id"];</code>
     */
    protected $id = '';
    /**
     * Generated from protobuf field <code>string identity_id = 2[json_name = "identityId"];</code>
     */
    protected $identity_id = '';
    /**
     * Generated from protobuf field <code>string status = 3[json_name = "status"];</code>
     */
    protected $status = '';
    /**
     * Generated from protobuf field <code>repeated string authentication_methods = 4[json_name = "authenticationMethods"];</code>
     */
    private $authentication_methods;
    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp created_at = 5[json_name = "createdAt"];</code>
     */
    protected $created_at = null;
    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp expires_at = 6[json_name = "expiresAt"];</code>
     */
    protected $expires_at = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $id
     *     @type string $identity_id
     *     @type string $status
     *     @type string[]|\Google\Protobuf\Internal\RepeatedField $authentication_methods
     *     @type \Google\Protobuf\Timestamp $created_at
     *     @type \Google\Protobuf\Timestamp $expires_at
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Devtools\Auth\V0\Proto\Identity\Admin\Admin::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string id = 1[json_name = "id"];</code>
     * @return string
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Generated from protobuf field <code>string id = 1[json_name = "id"];</code>
     * @param string $var
     * @return $this
     */
    public function setId($var)
    {
        GPBUtil::checkString($var, True);
        $this->id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string identity_id = 2[json_name = "identityId"];</code>
     * @return string
     */
    public function getIdentityId()
    {
        return $this->identity_id;
    }

    /**
     * Generated from protobuf field <code>string identity_id = 2[json_name = "identityId"];</code>
     * @param string $var
     * @return $this
     */
    public function setIdentityId($var)
    {
        GPBUtil::checkString($var, True);
        $this->identity_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string status = 3[json_name = "status"];</code>
     * @return string
     */
    public function getStatus()
    {
        return $this->status;
    }

    /**
     * Generated from protobuf field <code>string status = 3[json_name = "status"];</code>
     * @param string $var
     * @return $this
     */
    public function setStatus($var)
    {
        GPBUtil::checkString($var, True);
        $this->status = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated string authentication_methods = 4[json_name = "authenticationMethods"];</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getAuthenticationMethods()
    {
        return $this->authentication_methods;
    }

    /**
     * Generated from protobuf field <code>repeated string authentication_methods = 4[json_name = "authenticationMethods"];</code>
     * @param string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setAuthenticationMethods($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->authentication_methods = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp created_at = 5[json_name = "createdAt"];</code>
     * @return \Google\Protobuf\Timestamp
     */
    public function getCreatedAt()
    {
        return $this->created_at;
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp created_at = 5[json_name = "createdAt"];</code>
     * @param \Google\Protobuf\Timestamp $var
     * @return $this
     */
    public function setCreatedAt($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Timestamp::class);
        $this->created_at = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp expires_at = 6[json_name = "expiresAt"];</code>
     * @return \Google\Protobuf\Timestamp
     */
    public function getExpiresAt()
    {
        return $this->expires_at;
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp expires_at = 6[json_name = "expiresAt"];</code>
     * @param \Google\Protobuf\Timestamp $var
     * @return $this
     */
    public function setExpiresAt($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Timestamp::class);
        $this->expires_at = $var;

        return $this;
    }

}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(Attempt::class, \Auth3\Identity\Admin\GetIdentityLoginAttemptsResponse_Attempt::class);

