<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: identity/admin/admin.proto

namespace Auth3\Identity\Admin\GetCredentialsResponse;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>depot.devtools.auth.v0.identity.admin.GetCredentialsResponse.Credential</code>
 */
class Credential extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string credential_id = 1[json_name = "credentialId"];</code>
     */
    protected $credential_id = '';
    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp created_at = 2[json_name = "createdAt"];</code>
     */
    protected $created_at = null;
    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp updated_at = 3[json_name = "updatedAt"];</code>
     */
    protected $updated_at = null;
    /**
     * Generated from protobuf field <code>string identity_id = 4[json_name = "identityId"];</code>
     */
    protected $identity_id = '';
    /**
     * Generated from protobuf field <code>int32 type = 5[json_name = "type"];</code>
     */
    protected $type = 0;
    /**
     * Generated from protobuf field <code>string connection_id = 6[json_name = "connectionId"];</code>
     */
    protected $connection_id = '';
    /**
     * Generated from protobuf field <code>bool configured = 7[json_name = "configured"];</code>
     */
    protected $configured = false;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $credential_id
     *     @type \Google\Protobuf\Timestamp $created_at
     *     @type \Google\Protobuf\Timestamp $updated_at
     *     @type string $identity_id
     *     @type int $type
     *     @type string $connection_id
     *     @type bool $configured
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Devtools\Auth\V0\Proto\Identity\Admin\Admin::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string credential_id = 1[json_name = "credentialId"];</code>
     * @return string
     */
    public function getCredentialId()
    {
        return $this->credential_id;
    }

    /**
     * Generated from protobuf field <code>string credential_id = 1[json_name = "credentialId"];</code>
     * @param string $var
     * @return $this
     */
    public function setCredentialId($var)
    {
        GPBUtil::checkString($var, True);
        $this->credential_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp created_at = 2[json_name = "createdAt"];</code>
     * @return \Google\Protobuf\Timestamp
     */
    public function getCreatedAt()
    {
        return $this->created_at;
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp created_at = 2[json_name = "createdAt"];</code>
     * @param \Google\Protobuf\Timestamp $var
     * @return $this
     */
    public function setCreatedAt($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Timestamp::class);
        $this->created_at = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp updated_at = 3[json_name = "updatedAt"];</code>
     * @return \Google\Protobuf\Timestamp
     */
    public function getUpdatedAt()
    {
        return $this->updated_at;
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp updated_at = 3[json_name = "updatedAt"];</code>
     * @param \Google\Protobuf\Timestamp $var
     * @return $this
     */
    public function setUpdatedAt($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Timestamp::class);
        $this->updated_at = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string identity_id = 4[json_name = "identityId"];</code>
     * @return string
     */
    public function getIdentityId()
    {
        return $this->identity_id;
    }

    /**
     * Generated from protobuf field <code>string identity_id = 4[json_name = "identityId"];</code>
     * @param string $var
     * @return $this
     */
    public function setIdentityId($var)
    {
        GPBUtil::checkString($var, True);
        $this->identity_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 type = 5[json_name = "type"];</code>
     * @return int
     */
    public function getType()
    {
        return $this->type;
    }

    /**
     * Generated from protobuf field <code>int32 type = 5[json_name = "type"];</code>
     * @param int $var
     * @return $this
     */
    public function setType($var)
    {
        GPBUtil::checkInt32($var);
        $this->type = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string connection_id = 6[json_name = "connectionId"];</code>
     * @return string
     */
    public function getConnectionId()
    {
        return $this->connection_id;
    }

    /**
     * Generated from protobuf field <code>string connection_id = 6[json_name = "connectionId"];</code>
     * @param string $var
     * @return $this
     */
    public function setConnectionId($var)
    {
        GPBUtil::checkString($var, True);
        $this->connection_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool configured = 7[json_name = "configured"];</code>
     * @return bool
     */
    public function getConfigured()
    {
        return $this->configured;
    }

    /**
     * Generated from protobuf field <code>bool configured = 7[json_name = "configured"];</code>
     * @param bool $var
     * @return $this
     */
    public function setConfigured($var)
    {
        GPBUtil::checkBool($var);
        $this->configured = $var;

        return $this;
    }

}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(Credential::class, \Auth3\Identity\Admin\GetCredentialsResponse_Credential::class);

