<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: identity/admin/admin.proto

namespace Auth3\Identity\Admin\GetIdentitiesByAttributeResponse;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>depot.devtools.auth.v0.identity.admin.GetIdentitiesByAttributeResponse.Identity</code>
 */
class Identity extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string identity_id = 1[json_name = "identityId"];</code>
     */
    protected $identity_id = '';
    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp created_at = 2[json_name = "createdAt"];</code>
     */
    protected $created_at = null;
    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp updated_at = 3[json_name = "updatedAt"];</code>
     */
    protected $updated_at = null;
    /**
     * Generated from protobuf field <code>string main_identifier = 4[json_name = "mainIdentifier"];</code>
     */
    protected $main_identifier = '';
    /**
     * Generated from protobuf field <code>string profile_id = 5[json_name = "profileId"];</code>
     */
    protected $profile_id = '';
    /**
     * Generated from protobuf field <code>repeated string addresses_ids = 6[json_name = "addressesIds"];</code>
     */
    private $addresses_ids;
    /**
     * Generated from protobuf field <code>map<string, string> credentials_ids = 7[json_name = "credentialsIds"];</code>
     */
    private $credentials_ids;
    /**
     * Generated from protobuf field <code>string schema_id = 8[json_name = "schemaId"];</code>
     */
    protected $schema_id = '';
    /**
     * Generated from protobuf field <code>.depot.devtools.auth.v0.identity.admin.GetIdentitiesByAttributeResponse.Identity.Lock lock = 9[json_name = "lock"];</code>
     */
    protected $lock = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $identity_id
     *     @type \Google\Protobuf\Timestamp $created_at
     *     @type \Google\Protobuf\Timestamp $updated_at
     *     @type string $main_identifier
     *     @type string $profile_id
     *     @type string[]|\Google\Protobuf\Internal\RepeatedField $addresses_ids
     *     @type array|\Google\Protobuf\Internal\MapField $credentials_ids
     *     @type string $schema_id
     *     @type int $lock
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Devtools\Auth\V0\Proto\Identity\Admin\Admin::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string identity_id = 1[json_name = "identityId"];</code>
     * @return string
     */
    public function getIdentityId()
    {
        return $this->identity_id;
    }

    /**
     * Generated from protobuf field <code>string identity_id = 1[json_name = "identityId"];</code>
     * @param string $var
     * @return $this
     */
    public function setIdentityId($var)
    {
        GPBUtil::checkString($var, True);
        $this->identity_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp created_at = 2[json_name = "createdAt"];</code>
     * @return \Google\Protobuf\Timestamp
     */
    public function getCreatedAt()
    {
        return $this->created_at;
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp created_at = 2[json_name = "createdAt"];</code>
     * @param \Google\Protobuf\Timestamp $var
     * @return $this
     */
    public function setCreatedAt($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Timestamp::class);
        $this->created_at = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp updated_at = 3[json_name = "updatedAt"];</code>
     * @return \Google\Protobuf\Timestamp
     */
    public function getUpdatedAt()
    {
        return $this->updated_at;
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp updated_at = 3[json_name = "updatedAt"];</code>
     * @param \Google\Protobuf\Timestamp $var
     * @return $this
     */
    public function setUpdatedAt($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Timestamp::class);
        $this->updated_at = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string main_identifier = 4[json_name = "mainIdentifier"];</code>
     * @return string
     */
    public function getMainIdentifier()
    {
        return $this->main_identifier;
    }

    /**
     * Generated from protobuf field <code>string main_identifier = 4[json_name = "mainIdentifier"];</code>
     * @param string $var
     * @return $this
     */
    public function setMainIdentifier($var)
    {
        GPBUtil::checkString($var, True);
        $this->main_identifier = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string profile_id = 5[json_name = "profileId"];</code>
     * @return string
     */
    public function getProfileId()
    {
        return $this->profile_id;
    }

    /**
     * Generated from protobuf field <code>string profile_id = 5[json_name = "profileId"];</code>
     * @param string $var
     * @return $this
     */
    public function setProfileId($var)
    {
        GPBUtil::checkString($var, True);
        $this->profile_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated string addresses_ids = 6[json_name = "addressesIds"];</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getAddressesIds()
    {
        return $this->addresses_ids;
    }

    /**
     * Generated from protobuf field <code>repeated string addresses_ids = 6[json_name = "addressesIds"];</code>
     * @param string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setAddressesIds($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->addresses_ids = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>map<string, string> credentials_ids = 7[json_name = "credentialsIds"];</code>
     * @return \Google\Protobuf\Internal\MapField
     */
    public function getCredentialsIds()
    {
        return $this->credentials_ids;
    }

    /**
     * Generated from protobuf field <code>map<string, string> credentials_ids = 7[json_name = "credentialsIds"];</code>
     * @param array|\Google\Protobuf\Internal\MapField $var
     * @return $this
     */
    public function setCredentialsIds($var)
    {
        $arr = GPBUtil::checkMapField($var, \Google\Protobuf\Internal\GPBType::STRING, \Google\Protobuf\Internal\GPBType::STRING);
        $this->credentials_ids = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string schema_id = 8[json_name = "schemaId"];</code>
     * @return string
     */
    public function getSchemaId()
    {
        return $this->schema_id;
    }

    /**
     * Generated from protobuf field <code>string schema_id = 8[json_name = "schemaId"];</code>
     * @param string $var
     * @return $this
     */
    public function setSchemaId($var)
    {
        GPBUtil::checkString($var, True);
        $this->schema_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.depot.devtools.auth.v0.identity.admin.GetIdentitiesByAttributeResponse.Identity.Lock lock = 9[json_name = "lock"];</code>
     * @return int
     */
    public function getLock()
    {
        return $this->lock;
    }

    /**
     * Generated from protobuf field <code>.depot.devtools.auth.v0.identity.admin.GetIdentitiesByAttributeResponse.Identity.Lock lock = 9[json_name = "lock"];</code>
     * @param int $var
     * @return $this
     */
    public function setLock($var)
    {
        GPBUtil::checkEnum($var, \Auth3\Identity\Admin\GetIdentitiesByAttributeResponse\Identity\Lock::class);
        $this->lock = $var;

        return $this;
    }

}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(Identity::class, \Auth3\Identity\Admin\GetIdentitiesByAttributeResponse_Identity::class);

