<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: identity/admin/admin.proto

namespace Auth3\Identity\Admin\GetEmailsSetupResponse;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>depot.devtools.auth.v0.identity.admin.GetEmailsSetupResponse.EmailSender</code>
 */
class EmailSender extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string email_address = 1[json_name = "emailAddress"];</code>
     */
    protected $email_address = '';
    /**
     * Generated from protobuf field <code>string smtp_host = 2[json_name = "smtpHost"];</code>
     */
    protected $smtp_host = '';
    /**
     * Generated from protobuf field <code>uint32 smtp_port = 3[json_name = "smtpPort"];</code>
     */
    protected $smtp_port = 0;
    /**
     * Generated from protobuf field <code>string smtp_username = 4[json_name = "smtpUsername"];</code>
     */
    protected $smtp_username = '';
    /**
     * Generated from protobuf field <code>string smtp_password = 5[json_name = "smtpPassword"];</code>
     */
    protected $smtp_password = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $email_address
     *     @type string $smtp_host
     *     @type int $smtp_port
     *     @type string $smtp_username
     *     @type string $smtp_password
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Devtools\Auth\V0\Proto\Identity\Admin\Admin::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string email_address = 1[json_name = "emailAddress"];</code>
     * @return string
     */
    public function getEmailAddress()
    {
        return $this->email_address;
    }

    /**
     * Generated from protobuf field <code>string email_address = 1[json_name = "emailAddress"];</code>
     * @param string $var
     * @return $this
     */
    public function setEmailAddress($var)
    {
        GPBUtil::checkString($var, True);
        $this->email_address = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string smtp_host = 2[json_name = "smtpHost"];</code>
     * @return string
     */
    public function getSmtpHost()
    {
        return $this->smtp_host;
    }

    /**
     * Generated from protobuf field <code>string smtp_host = 2[json_name = "smtpHost"];</code>
     * @param string $var
     * @return $this
     */
    public function setSmtpHost($var)
    {
        GPBUtil::checkString($var, True);
        $this->smtp_host = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 smtp_port = 3[json_name = "smtpPort"];</code>
     * @return int
     */
    public function getSmtpPort()
    {
        return $this->smtp_port;
    }

    /**
     * Generated from protobuf field <code>uint32 smtp_port = 3[json_name = "smtpPort"];</code>
     * @param int $var
     * @return $this
     */
    public function setSmtpPort($var)
    {
        GPBUtil::checkUint32($var);
        $this->smtp_port = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string smtp_username = 4[json_name = "smtpUsername"];</code>
     * @return string
     */
    public function getSmtpUsername()
    {
        return $this->smtp_username;
    }

    /**
     * Generated from protobuf field <code>string smtp_username = 4[json_name = "smtpUsername"];</code>
     * @param string $var
     * @return $this
     */
    public function setSmtpUsername($var)
    {
        GPBUtil::checkString($var, True);
        $this->smtp_username = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string smtp_password = 5[json_name = "smtpPassword"];</code>
     * @return string
     */
    public function getSmtpPassword()
    {
        return $this->smtp_password;
    }

    /**
     * Generated from protobuf field <code>string smtp_password = 5[json_name = "smtpPassword"];</code>
     * @param string $var
     * @return $this
     */
    public function setSmtpPassword($var)
    {
        GPBUtil::checkString($var, True);
        $this->smtp_password = $var;

        return $this;
    }

}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(EmailSender::class, \Auth3\Identity\Admin\GetEmailsSetupResponse_EmailSender::class);

